apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
  namespace: flux-system
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - gekko-hetzner-2
                      - gekko-hetzner-3
                      - gekko-hetzner-4
