// scripts/agent-guide/emit-maps.mjs
// Emitter for the agent-guide repo-map surface (S3).
// validateRegistry -> loadRegistry -> render 3 pure templates -> write docs/agent-guide/maps/*.md.
// No YAML parsing of its own: it depends on S1's scripts/agent-guide/load.mjs.

export const HEADER =
  '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-maps.mjs; edit the registry -->';

export const EMPTY = '—';

/**
 * Make any value safe inside a GFM table cell.
 * - collapse any whitespace run containing a newline to a single space
 * - replace each `|` with `\|`
 * - trim
 * Empty/undefined renders as the em-dash placeholder.
 * @param {unknown} value
 * @returns {string}
 */
export function escapeCell(value) {
  if (value === undefined || value === null) return EMPTY;
  let s = String(value);
  s = s.replace(/\s*[\r\n]+\s*/g, ' '); // newline-containing whitespace runs -> one space
  s = s.replace(/\|/g, '\\|');
  s = s.trim();
  return s === '' ? EMPTY : s;
}

// Render one GFM table row from already-escaped cell strings.
function row(cells) {
  return `| ${cells.join(' | ')} |`;
}

// Resolve a danger id to "emoji label_de" via tierFor; throw (fail-closed) if unknown.
function tierLabel(reg, dangerId) {
  const t = reg.tierFor(dangerId);
  if (!t) throw new Error(`render: danger id "${dangerId}" has no taxonomy entry`);
  return `${t.emoji} ${t.label_de}`;
}

// Join guardrail ids (validating each resolves), em-dash for empty.
function guardrailIds(reg, ids) {
  if (!ids || ids.length === 0) return EMPTY;
  for (const id of ids) {
    if (!reg.guardrailById(id)) throw new Error(`guardrail id "${id}" has no guardrails.yaml entry`);
  }
  return ids.join(', ');
}

/**
 * Render goals-map.md from an in-memory registry (shape of loadRegistry()).
 * @param {ReturnType<import('./load.mjs').loadRegistry>} reg
 * @returns {string}
 */
export function renderGoalsMap(reg) {
  const goals = [...reg.goals].sort((a, b) => a.id.localeCompare(b.id));
  const out = [];
  out.push(HEADER);
  out.push('');
  out.push('# Ziel-Karte (Goals Map)');
  out.push('');
  out.push('Diese Datei ist die Routing-Karte für Agenten und Operator: Intention → Weg → Gefahr → Regeln.');
  out.push('Die Tier-Emojis (🟢🟡🟠🔴) sind in `danger-map.md` erklärt, die Werkzeug-Ids in `tools-map.md`.');
  out.push('');
  out.push(row(['Ich will …', 'Weg (Flow)', 'Tier', 'Guardrails', 'Prompt']));
  out.push(row(['---', '---', '---', '---', '---']));
  for (const g of goals) {
    const flowIds = (g.flow || []).map((f) => {
      if (!reg.toolById(f.tool)) throw new Error(`renderGoalsMap: flow tool id "${f.tool}" has no tools.yaml entry`);
      return f.tool;
    });
    const flowCell = flowIds.length ? flowIds.join(' → ') : EMPTY;
    out.push(
      row([
        escapeCell(g.title_de),
        escapeCell(flowCell),
        escapeCell(tierLabel(reg, g.danger)),
        escapeCell(guardrailIds(reg, g.guardrails)),
        escapeCell(g.example_prompt_de),
      ])
    );
  }
  return out.join('\n') + '\n';
}
// Fixed section order with German headings; key is tool.kind.
const TOOL_SECTIONS = [
  { kind: 'skill', heading: 'Skills' },
  { kind: 'task', heading: 'Tasks' },
  { kind: 'agent', heading: 'Agenten' },
];

/**
 * Render tools-map.md from an in-memory registry.
 * @param {ReturnType<import('./load.mjs').loadRegistry>} reg
 * @returns {string}
 */
export function renderToolsMap(reg) {
  const out = [];
  out.push(HEADER);
  out.push('');
  out.push('# Werkzeug-Karte (Tools Map)');
  out.push('');
  out.push('Kompakte Referenz der Skills, Tasks und Routing-Agenten: Id, Art, Gefahren-Tier, Wofür.');
  out.push('Die Tier-Emojis (🟢🟡🟠🔴) sind in `danger-map.md` erklärt.');
  for (const section of TOOL_SECTIONS) {
    const rows = reg.tools
      .filter((t) => t.kind === section.kind)
      .sort((a, b) => a.id.localeCompare(b.id));
    out.push('');
    out.push(`## ${section.heading}`);
    out.push('');
    out.push(row(['Id', 'Name', 'Art', 'Tier', 'Wofür', 'Guardrails']));
    out.push(row(['---', '---', '---', '---', '---', '---']));
    for (const t of rows) {
      out.push(
        row([
          escapeCell(t.id),
          escapeCell(t.name_de),
          escapeCell(t.kind),
          escapeCell(tierLabel(reg, t.danger)),
          escapeCell(t.summary_de),
          escapeCell(guardrailIds(reg, t.guardrails)),
        ])
      );
    }
  }
  return out.join('\n') + '\n';
}
export function renderDangerMap() {
  throw new Error('renderDangerMap not implemented yet');
}
