// scripts/agent-guide/emit-docs.mjs
import { tierFor, toolById, guardrailById, loadRegistry } from './load.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The six routing agents whose tools.yaml ids are agent-<x> but whose
 *  discovered page slug is bachelorprojekt-<x>. */
const AGENT_SUFFIXES = new Set(['website', 'ops', 'infra', 'test', 'db', 'security']);

/** The four beginner-spine skills whose ids equal their SKILL.md slug. */
const SPINE_SKILLS = new Set([
  'dev-flow-plan', 'dev-flow-execute', 'dev-flow-iterate', 'dev-flow-e2e',
]);

/**
 * Map a tools.yaml id to the slug the docs generator will discover, or null
 * when no discoverable page exists (→ caller emits a plain link, not [[…]]).
 * @param {string} id
 * @returns {string|null}
 */
export function slugForToolId(id) {
  if (SPINE_SKILLS.has(id)) return id;
  const m = /^agent-([a-z]+)$/.exec(id || '');
  if (m && AGENT_SUFFIXES.has(m[1])) return `bachelorprojekt-${m[1]}`;
  return null;
}

/**
 * Build the fence-first frontmatter + DO-NOT-EDIT comment header.
 * Line 1 is exactly "---"; the comment is the FIRST body line (spec §6).
 * @param {string} title  frontmatter title (quoted in YAML)
 * @param {string} h1     the page H1 text (rendered after the comment)
 * @returns {string}  header ending with a trailing newline after the H1
 */
export function renderHeader(title, h1) {
  return [
    '---',
    `title: ${JSON.stringify(title)}`,
    'domain: general',
    'generated_by: scripts/agent-guide/emit-docs.mjs',
    '---',
    '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-docs.mjs -->',
    `# ${h1}`,
    '',
  ].join('\n');
}

/**
 * Render a danger badge "emoji **label_de**" from a taxonomy id. Unknown ids
 * degrade to "⚪ **<id>**" so a dangling danger ref is visible, never blank.
 * @param {string} dangerId
 * @returns {string}
 */
export function dangerBadge(dangerId) {
  const tier = tierFor(dangerId);
  if (!tier) return `⚪ **${dangerId}**`;
  return `${tier.emoji} **${tier.label_de}**`;
}

/** First links[].url for a tool, or '' when absent. */
function firstLinkUrl(tool) {
  const links = Array.isArray(tool && tool.links) ? tool.links : [];
  const first = links.find((l) => l && typeof l.url === 'string' && l.url.trim());
  return first ? first.url : '';
}

/**
 * Render a tool reference: a [[slug]] wikilink when discoverable, otherwise a
 * plain [name_de](url) link (or the bare name_de when no url exists).
 * @param {string} toolId
 * @returns {string}
 */
export function toolLink(toolId) {
  const slug = slugForToolId(toolId);
  if (slug) return `[[${slug}]]`;
  const tool = toolById(toolId);
  const label = tool ? tool.name_de : toolId;
  const url = tool ? firstLinkUrl(tool) : '';
  return url ? `[${label}](${url})` : label;
}

/**
 * Render a plain markdown link, or '' when the url is blank.
 * @param {string} label
 * @param {string} url
 * @returns {string}
 */
export function urlLink(label, url) {
  const u = (url || '').trim();
  return u ? `[${label}](${u})` : '';
}
