// scripts/agent-guide/emit-maps.mjs
// Emitter for the agent-guide repo-map surface (S3).
// validateRegistry -> loadRegistry -> render 3 pure templates -> write docs/agent-guide/maps/*.md.
// No YAML parsing of its own: it depends on S1's scripts/agent-guide/load.mjs.

import { mkdir, writeFile, rename } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/**
 * Atomically write `body` to `dest` via tmp-file + rename.
 * Prevents readers (concurrent git checkout, hooks, watchers) from observing
 * a half-written or empty file when this emitter is interrupted mid-write.
 * The previous non-atomic writeFile truncated dest to 0 bytes before writing,
 * so any concurrent reader that opened dest after the truncate but before the
 * write finished saw an empty file. Now: tmp lives next to dest, rename(2) is
 * atomic on POSIX so dest jumps from old content to new content in one step.
 */
async function atomicWriteFile(dest, body) {
  const tmp = `${dest}.${randomBytes(6).toString('hex')}.tmp`;
  try {
    await writeFile(tmp, body, 'utf8');
    await rename(tmp, dest);
  } catch (err) {
    // Best-effort cleanup of the tmp on failure; ignore ENOENT (already gone).
    try { await rename(tmp, dest); } catch { /* ignore */ }
    throw err;
  }
}

// S1's shared reader (merged): the single YAML parse is routed through load.mjs.
// loadRegistry returns the five arrays; tierFor/toolById/guardrailById are module-level
// helpers that read the just-loaded registry (they are NOT methods on the returned object).
import { loadRegistry, tierFor, toolById, guardrailById } from './load.mjs';

export const HEADER =
  '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-maps.mjs; edit the registry -->';

export const EMPTY = '—';

/**
 * Make any value safe inside a GFM table cell.
 * - collapse any whitespace run containing a newline to a single space
 * - replace each `|` with `\|`
 * - trim
 * Empty/undefined renders as the em-dash placeholder.
 * @param {unknown} value
 * @returns {string}
 */
export function escapeCell(value) {
  if (value === undefined || value === null) return EMPTY;
  let s = String(value);
  s = s.replace(/\s*[\r\n]+\s*/g, ' '); // newline-containing whitespace runs -> one space
  s = s.replace(/\|/g, '\\|');
  s = s.trim();
  return s === '' ? EMPTY : s;
}

// Render one GFM table row from already-escaped cell strings.
function row(cells) {
  return `| ${cells.join(' | ')} |`;
}

// Render a taxonomy entry as "emoji label" exactly once. taxonomy.yaml's label_de already
// embeds the tier emoji (e.g. "🟡 Vorsicht") matching the separate emoji field; strip the
// leading emoji so we don't double-print it (mirrors S1's dangerBadge). A fixture label_de
// without a leading emoji (unit tests) is unaffected.
function tierText(tier) {
  const label = String(tier.label_de).replace(/^\p{Emoji_Presentation}\s*/u, '');
  return `${tier.emoji} ${label}`;
}

// Resolve a danger id to "emoji label" via tierFor; throw (fail-closed) if unknown.
function tierLabel(reg, dangerId) {
  const t = reg.tierFor(dangerId);
  if (!t) throw new Error(`render: danger id "${dangerId}" has no taxonomy entry`);
  return tierText(t);
}

// Join guardrail ids (validating each resolves), em-dash for empty.
// Sorted by id so a row renders byte-identically regardless of registry input
// order — the determinism invariant (matches renderDangerMap's guardrail sort).
function guardrailIds(reg, ids) {
  if (!ids || ids.length === 0) return EMPTY;
  for (const id of ids) {
    if (!reg.guardrailById(id)) throw new Error(`guardrail id "${id}" has no guardrails.yaml entry`);
  }
  return [...ids].sort((a, b) => a.localeCompare(b)).join(', ');
}

/**
 * Render goals-map.md from an in-memory registry (shape of loadRegistry()).
 * @param {ReturnType<import('./load.mjs').loadRegistry>} reg
 * @returns {string}
 */
export function renderGoalsMap(reg) {
  const goals = [...reg.goals].sort((a, b) => a.id.localeCompare(b.id));
  const out = [];
  out.push(HEADER);
  out.push('');
  out.push('# Ziel-Karte (Goals Map)');
  out.push('');
  out.push('Diese Datei ist die Routing-Karte für Agenten und Operator: Intention → Weg → Gefahr → Regeln.');
  out.push('Die Tier-Emojis (🟢🟡🟠🔴) sind in `danger-map.md` erklärt, die Werkzeug-Ids in `tools-map.md`.');
  out.push('');
  out.push(row(['Ich will …', 'Weg (Flow)', 'Tier', 'Guardrails', 'Prompt']));
  out.push(row(['---', '---', '---', '---', '---']));
  for (const g of goals) {
    const flowIds = (g.flow || []).map((f) => {
      if (!reg.toolById(f.tool)) throw new Error(`renderGoalsMap: flow tool id "${f.tool}" has no tools.yaml entry`);
      return f.tool;
    });
    const flowCell = flowIds.length ? flowIds.join(' → ') : EMPTY;
    out.push(
      row([
        escapeCell(g.title_de),
        escapeCell(flowCell),
        escapeCell(tierLabel(reg, g.danger)),
        escapeCell(guardrailIds(reg, g.guardrails)),
        escapeCell(g.example_prompt_de),
      ])
    );
  }
  return out.join('\n') + '\n';
}
// Fixed section order with German headings; key is tool.kind.
const TOOL_SECTIONS = [
  { kind: 'skill', heading: 'Skills' },
  { kind: 'task', heading: 'Tasks' },
  { kind: 'agent', heading: 'Agenten' },
];

/**
 * Render tools-map.md from an in-memory registry.
 * @param {ReturnType<import('./load.mjs').loadRegistry>} reg
 * @returns {string}
 */
export function renderToolsMap(reg) {
  const out = [];
  out.push(HEADER);
  out.push('');
  out.push('# Werkzeug-Karte (Tools Map)');
  out.push('');
  out.push('Kompakte Referenz der Skills, Tasks und Routing-Agenten: Id, Art, Gefahren-Tier, Wofür.');
  out.push('Die Tier-Emojis (🟢🟡🟠🔴) sind in `danger-map.md` erklärt.');
  for (const section of TOOL_SECTIONS) {
    const rows = reg.tools
      .filter((t) => t.kind === section.kind)
      .sort((a, b) => a.id.localeCompare(b.id));
    out.push('');
    out.push(`## ${section.heading}`);
    out.push('');
    out.push(row(['Id', 'Name', 'Art', 'Harness', 'Tier', 'Wofür', 'Guardrails', 'Init']));
    out.push(row(['---', '---', '---', '---', '---', '---', '---', '---']));
    for (const t of rows) {
      out.push(
        row([
          escapeCell(t.id),
          escapeCell(t.name_de),
          escapeCell(t.kind),
          escapeCell(t.harness),
          escapeCell(tierLabel(reg, t.danger)),
          escapeCell(t.summary_de),
          escapeCell(guardrailIds(reg, t.guardrails)),
          escapeCell(t.init_prompt_de),
        ])
      );
    }
  }
  return out.join('\n') + '\n';
}
// Canonical tier order, independent of taxonomy.yaml file order.
export const TIER_ORDER = ['safe', 'caution', 'assisted', 'forbidden'];

/**
 * Render danger-map.md from an in-memory registry.
 * Guardrail tiers are derived transitively from referencing goals/tools.
 * @param {ReturnType<import('./load.mjs').loadRegistry>} reg
 * @returns {string}
 */
export function renderDangerMap(reg) {
  const out = [];
  out.push(HEADER);
  out.push('');
  out.push('# Gefahren-Karte (Danger Map)');
  out.push('');
  out.push('Die vier Gefahren-Stufen und was unter jede fällt — die Vorschau auf den Enforcement-Kontrakt.');
  out.push('Hinweis: Eine Guardrail hat **keine** eigene Stufe; sie erscheint unter **jeder** Stufe, deren');
  out.push('Ziele/Werkzeuge sie referenzieren (transitiv) — also ggf. unter mehreren Stufen.');

  for (const tierId of TIER_ORDER) {
    const tier = reg.tierFor(tierId);
    if (!tier) throw new Error(`renderDangerMap: taxonomy has no entry for tier "${tierId}"`);

    const goalsHere = reg.goals
      .filter((g) => g.danger === tierId)
      .sort((a, b) => a.id.localeCompare(b.id));
    const toolsHere = reg.tools
      .filter((t) => t.danger === tierId)
      .sort((a, b) => a.id.localeCompare(b.id));

    // transitive, de-duplicated guardrail ids referenced by goals/tools of this tier
    const grSet = new Set();
    for (const g of goalsHere) for (const id of g.guardrails || []) grSet.add(id);
    for (const t of toolsHere) for (const id of t.guardrails || []) grSet.add(id);
    const grIds = [...grSet].sort((a, b) => a.localeCompare(b));

    out.push('');
    out.push(`## ${tierText(tier)} — ${tier.meaning_de}`);
    out.push('');
    out.push(`**enforcement_default:** \`${tier.enforcement_default}\``);
    out.push('');
    out.push('**Ziele:**');
    if (goalsHere.length === 0) {
      out.push('- —');
    } else {
      for (const g of goalsHere) out.push(`- \`${g.id}\` — ${escapeCell(g.title_de)}`);
    }
    out.push('');
    out.push('**Werkzeuge:**');
    if (toolsHere.length === 0) {
      out.push('- —');
    } else {
      for (const t of toolsHere) out.push(`- \`${t.id}\` — ${escapeCell(t.name_de)}`);
    }
    out.push('');
    out.push('**Guardrails (transitiv):**');
    if (grIds.length === 0) {
      out.push('- —');
    } else {
      for (const id of grIds) {
        const gr = reg.guardrailById(id);
        if (!gr) throw new Error(`renderDangerMap: guardrail id "${id}" has no guardrails.yaml entry`);
        out.push(`- \`${id}\` — ${escapeCell(gr.name_de)}`);
      }
    }
  }
  return out.join('\n') + '\n';
}

/**
 * Validate-first, then build all three maps and write them under mapsDir.
 * Mirrors S1's writeDocs: aborts (throws) on an invalid registry so we never
 * emit maps from bad input. The danger-map count uses TIER_ORDER.length (always
 * the 4 tiers renderDangerMap emits), not reg.taxonomy.length which would mislead on drift.
 * @param {{ registryDir: string, mapsDir: string, repoRoot: string,
 *           validate: (dir:string, repoRoot:string)=>{ok:boolean, errors:string[]} }} opts
 */
export async function emitAll({ registryDir, mapsDir, repoRoot, validate }) {
  const result = validate(registryDir, repoRoot);
  if (!result || result.ok !== true) {
    const errs = (result && result.errors) ? result.errors.join('; ') : 'unknown error';
    throw new Error(`agent-guide: refusing to emit maps from an invalid registry: ${errs}`);
  }
  // Bridge the real load.mjs shape to what the pure render functions expect: the unit-test
  // fixtures pass tierFor/toolById/guardrailById as methods on the registry object, but S1's
  // loadRegistry returns only the arrays and exposes those helpers as module-level functions
  // reading the just-loaded registry. Attaching them here keeps the renderers fixture-testable.
  const reg = { ...loadRegistry(registryDir), tierFor, toolById, guardrailById };
  const files = [
    { name: 'goals-map.md', body: renderGoalsMap(reg), count: reg.goals.length, unit: 'goal rows' },
    { name: 'tools-map.md', body: renderToolsMap(reg), count: reg.tools.length, unit: 'tool rows' },
    { name: 'danger-map.md', body: renderDangerMap(reg), count: TIER_ORDER.length, unit: 'tiers' },
  ];
  await mkdir(mapsDir, { recursive: true });
  for (const f of files) {
    const dest = join(mapsDir, f.name);
    await atomicWriteFile(dest, f.body);
    console.log(`Wrote ${f.count} ${f.unit} to ${dest}`);
  }
}

// CLI entrypoint (robust against paths with spaces via pathToFileURL).
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const here = dirname(fileURLToPath(import.meta.url));        // scripts/agent-guide
  const repoRoot = join(here, '..', '..');                    // repo root
  const registryDir = join(repoRoot, 'docs', 'agent-guide', 'registry');
  const mapsDir = join(repoRoot, 'docs', 'agent-guide', 'maps');

  // Fail-closed: validate before writing anything (same validator F+B/S1 use).
  const { validateRegistry } = await import('./validate.mjs');
  const validate = (dir, root) => {
    const { ok, errors } = validateRegistry(dir, root);
    return { ok, errors };
  };

  emitAll({ registryDir, mapsDir, repoRoot, validate }).catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}
