// scripts/agent-guide/emit-maps.mjs
// Emitter for the agent-guide repo-map surface (S3).
// validateRegistry -> loadRegistry -> render 3 pure templates -> write docs/agent-guide/maps/*.md.
// No YAML parsing of its own: it depends on S1's scripts/agent-guide/load.mjs.

export const HEADER =
  '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-maps.mjs; edit the registry -->';

export const EMPTY = '—';

/**
 * Make any value safe inside a GFM table cell.
 * - collapse any whitespace run containing a newline to a single space
 * - replace each `|` with `\|`
 * - trim
 * Empty/undefined renders as the em-dash placeholder.
 * @param {unknown} value
 * @returns {string}
 */
export function escapeCell(value) {
  if (value === undefined || value === null) return EMPTY;
  let s = String(value);
  s = s.replace(/\s*[\r\n]+\s*/g, ' '); // newline-containing whitespace runs -> one space
  s = s.replace(/\|/g, '\\|');
  s = s.trim();
  return s === '' ? EMPTY : s;
}

// Stubs — implemented in later tasks. Present so the test module's imports resolve.
export function renderGoalsMap() {
  throw new Error('renderGoalsMap not implemented yet');
}
export function renderToolsMap() {
  throw new Error('renderToolsMap not implemented yet');
}
export function renderDangerMap() {
  throw new Error('renderDangerMap not implemented yet');
}
