// scripts/agent-guide/emit-docs.mjs
import { tierFor, toolById, guardrailById, goalById, loadRegistry } from './load.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/** The six routing agents whose tools.yaml ids are agent-<x> but whose
 *  discovered page slug is bachelorprojekt-<x>. */
const AGENT_SUFFIXES = new Set(['website', 'ops', 'infra', 'test', 'db', 'security']);

/** The four beginner-spine skills whose ids equal their SKILL.md slug. */
const SPINE_SKILLS = new Set([
  'dev-flow-plan', 'dev-flow-execute', 'dev-flow-iterate', 'dev-flow-e2e',
]);

/**
 * Map a tools.yaml id to the slug the docs generator will discover, or null
 * when no discoverable page exists (→ caller emits a plain link, not [[…]]).
 * @param {string} id
 * @returns {string|null}
 */
export function slugForToolId(id) {
  if (SPINE_SKILLS.has(id)) return id;
  const m = /^agent-([a-z]+)$/.exec(id || '');
  if (m && AGENT_SUFFIXES.has(m[1])) return `bachelorprojekt-${m[1]}`;
  return null;
}

/**
 * Build the fence-first frontmatter + DO-NOT-EDIT comment header.
 * Line 1 is exactly "---"; the comment is the FIRST body line (spec §6).
 * @param {string} title  frontmatter title (quoted in YAML)
 * @param {string} h1     the page H1 text (rendered after the comment)
 * @returns {string}  header ending with a trailing newline after the H1
 */
export function renderHeader(title, h1) {
  return [
    '---',
    `title: ${JSON.stringify(title)}`,
    'domain: general',
    'generated_by: scripts/agent-guide/emit-docs.mjs',
    '---',
    '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-docs.mjs -->',
    `# ${h1}`,
    '',
  ].join('\n');
}

/**
 * Render a danger badge "emoji **label_de**" from a taxonomy id. Unknown ids
 * degrade to "⚪ **<id>**" so a dangling danger ref is visible, never blank.
 * @param {string} dangerId
 * @returns {string}
 */
export function dangerBadge(dangerId) {
  const tier = tierFor(dangerId);
  if (!tier) return `⚪ **${dangerId}**`;
  // taxonomy.yaml stores label_de as e.g. "🟢 Sicher" (emoji + space + text)
  // matching the separate emoji field; strip the leading emoji so the badge
  // renders as `emoji **text**` without double-printing the emoji.
  const label = tier.label_de.replace(/^\p{Emoji_Presentation}\s*/u, '');
  return `${tier.emoji} **${label}**`;
}

/** First links[].url for a tool, or '' when absent. */
function firstLinkUrl(tool) {
  const links = Array.isArray(tool && tool.links) ? tool.links : [];
  const first = links.find((l) => l && typeof l.url === 'string' && l.url.trim());
  return first ? first.url : '';
}

/**
 * Render a tool reference: a [[slug]] wikilink when discoverable, otherwise a
 * plain [name_de](url) link (or the bare name_de when no url exists).
 * @param {string} toolId
 * @returns {string}
 */
export function toolLink(toolId) {
  const slug = slugForToolId(toolId);
  if (slug) return `[[${slug}]]`;
  const tool = toolById(toolId);
  const label = tool ? tool.name_de : toolId;
  const url = tool ? firstLinkUrl(tool) : '';
  return url ? `[${label}](${url})` : label;
}

/**
 * Render a plain markdown link, or '' when the url is blank.
 * @param {string} label
 * @param {string} url
 * @returns {string}
 */
export function urlLink(label, url) {
  const u = (url || '').trim();
  return u ? `[${label}](${u})` : '';
}

/** Kind id → German pill label. */
const KIND_LABEL = { skill: 'Skill', agent: 'Agent', task: 'Task' };

/**
 * Render a comma-separated list of guardrail names from ids; '' when none.
 * Unknown ids fall back to the raw id so a dangling ref is visible.
 * @param {string[]} ids
 * @returns {string}
 */
function guardrailNames(ids) {
  const list = Array.isArray(ids) ? ids : [];
  if (list.length === 0) return '';
  return list.map((id) => {
    const g = guardrailById(id);
    return g ? `${g.name_de} (${id})` : id;
  }).join(', ');
}

/**
 * Lens 1 — the goal catalog (10-ziele.md). One H2 per goal in file order.
 * @param {{goals: object[]}} reg
 * @returns {string}
 */
export function renderZiele(reg) {
  const parts = [renderHeader('Ziele — Was will ich tun?', 'Ziele — „Ich will …"')];
  parts.push([
    '> Diese Seite wird automatisch aus der Registry erzeugt',
    '> (`docs/agent-guide/registry/goals.yaml`). Nicht von Hand bearbeiten.',
    '> Zur Erklärung der Linsen: [[00-anleitung]].',
    '',
  ].join('\n'));
  for (const goal of reg.goals) {
    parts.push(`## ${goal.title_de}`);
    parts.push('');
    parts.push(`${dangerBadge(goal.danger)}`);
    parts.push('');
    parts.push(`**Wann?** ${goal.when_de}`);
    parts.push('');
    parts.push('**So gehst du vor:**');
    parts.push('');
    const flow = Array.isArray(goal.flow) ? goal.flow : [];
    flow.forEach((step, i) => {
      parts.push(`${i + 1}. ${toolLink(step.tool)} — ${step.note_de}`);
    });
    parts.push('');
    parts.push('**Diesen Prompt kannst du der KI geben:**');
    parts.push('');
    parts.push('```text');
    parts.push(goal.example_prompt_de);
    parts.push('```');
    parts.push('');
    const gr = guardrailNames(goal.guardrails);
    if (gr) {
      parts.push(`**Schutzregeln (Guardrails):** ${gr}`);
      parts.push('');
    }
    const relatedGoals = Array.isArray(goal.related) ? goal.related : [];
    if (relatedGoals.length) {
      const names = relatedGoals.map((id) => {
        const g = goalById(id);
        return g ? g.title_de : id;
      });
      parts.push(`**Verwandte Ziele:** ${names.join(', ')}`);
      parts.push('');
    }
  }
  return parts.join('\n');
}

/**
 * Lens 2 — tool + agent reference cards (20-werkzeuge.md). One H2 per tool.
 * @param {{tools: object[]}} reg
 * @returns {string}
 */
export function renderWerkzeuge(reg) {
  const parts = [renderHeader('Werkzeuge — Tools und Agents', 'Werkzeuge — Tools und Agents')];
  parts.push([
    '> Diese Seite wird automatisch aus der Registry erzeugt',
    '> (`docs/agent-guide/registry/tools.yaml`). Nicht von Hand bearbeiten.',
    '> Zurück zur Übersicht: [[00-anleitung]].',
    '',
  ].join('\n'));
  for (const tool of reg.tools) {
    parts.push(`## ${tool.name_de}`);
    parts.push('');
    parts.push(`**${KIND_LABEL[tool.kind] || tool.kind}** · ${dangerBadge(tool.danger)}`);
    parts.push('');
    parts.push(tool.summary_de);
    parts.push('');
    parts.push(`**Wofür?** ${tool.what_for_de}`);
    parts.push('');
    parts.push(`**So startest du:** ${tool.how_to_start_de}`);
    parts.push('');
    parts.push(`**Was schiefgehen kann:** ${tool.what_could_go_wrong_de}`);
    parts.push('');
    if (typeof tool.init_prompt_de === 'string' && tool.init_prompt_de.trim()) {
      parts.push('**Du kannst diesen Prompt kopieren und in Claude Code einfügen:**');
      parts.push('');
      parts.push('```text');
      parts.push(tool.init_prompt_de);
      parts.push('```');
      parts.push('');
    }
    const gr = guardrailNames(tool.guardrails);
    if (gr) {
      parts.push(`**Schutzregeln (Guardrails):** ${gr}`);
      parts.push('');
    }
    const related = Array.isArray(tool.related) ? tool.related : [];
    if (related.length) {
      parts.push(`**Verwandt:** ${related.map((id) => toolLink(id)).join(', ')}`);
      parts.push('');
    }
    const links = Array.isArray(tool.links) ? tool.links : [];
    const linkMd = links
      .filter((l) => l && l.url)
      .map((l) => urlLink(l.label || l.url, l.url))
      .filter(Boolean);
    if (linkMd.length) {
      parts.push(`**Mehr dazu:** ${linkMd.join(' · ')}`);
      parts.push('');
    }
  }
  return parts.join('\n');
}

/**
 * Lens 3 — platform components (30-bausteine.md). Software-first then hardware,
 * each group iterated in registry file order.
 * @param {{components: object[]}} reg
 * @returns {string}
 */
export function renderBausteine(reg) {
  const parts = [renderHeader('Bausteine — Was läuft auf der Plattform?', 'Bausteine — Was läuft auf der Plattform?')];
  parts.push([
    '> Diese Seite wird automatisch aus der Registry erzeugt',
    '> (`docs/agent-guide/registry/components.yaml`). Nicht von Hand bearbeiten.',
    '> Zurück zur Übersicht: [[00-anleitung]].',
    '',
  ].join('\n'));
  const software = reg.components.filter((c) => c.kind === 'software');
  const hardware = reg.components.filter((c) => c.kind === 'hardware');
  // H2 for group headers ("Software"/"Hardware") and H3 for individual items
  // avoids a second H1 competing with the page H1, and keeps the on-page TOC
  // showing only the two top-level groups rather than every component.
  const renderGroup = (title, list) => {
    parts.push(`## ${title}`);
    parts.push('');
    for (const c of list) {
      parts.push(`### ${c.emoji} ${c.name}`);
      parts.push('');
      parts.push(`${dangerBadge(c.sensitivity)}`);
      parts.push('');
      parts.push(c.what_for_de);
      parts.push('');
      const extra = Array.isArray(c.links) ? c.links : [];
      const linkMd = [urlLink(c.name, c.url || '')]
        .concat(extra.filter((l) => l && l.url).map((l) => urlLink(l.label || l.url, l.url)))
        .filter(Boolean);
      if (linkMd.length) {
        parts.push(`**Mehr dazu:** ${linkMd.join(' · ')}`);
        parts.push('');
      }
    }
  };
  renderGroup('Software', software);
  renderGroup('Hardware', hardware);
  return parts.join('\n');
}

/**
 * Render all three generated pages into a { slug: markdown } map.
 * @param {object} reg  the loaded registry
 * @returns {{ '10-ziele': string, '20-werkzeuge': string, '30-bausteine': string }}
 */
export function renderAll(reg) {
  return {
    '10-ziele': renderZiele(reg),
    '20-werkzeuge': renderWerkzeuge(reg),
    '30-bausteine': renderBausteine(reg),
  };
}

/**
 * Validate-first, then write the generated trio to <outDir>/<slug>.md.
 * Never writes 00-anleitung.md (hand-authored). Aborts (throws) on an invalid
 * registry so we never emit from bad input.
 * @param {{ registryDir: string, outDir: string, repoRoot: string,
 *           validate: (dir:string, repoRoot:string)=>{ok:boolean, errors:string[]} }} opts
 */
export function writeDocs({ registryDir, outDir, repoRoot, validate }) {
  const result = validate(registryDir, repoRoot);
  if (!result || result.ok !== true) {
    const errs = (result && result.errors) ? result.errors.join('; ') : 'unknown error';
    throw new Error(`agent-guide: refusing to emit from an invalid registry: ${errs}`);
  }
  const reg = loadRegistry(registryDir);
  const pages = renderAll(reg);
  mkdirSync(outDir, { recursive: true });
  for (const [slug, md] of Object.entries(pages)) {
    writeFileSync(join(outDir, `${slug}.md`), md, 'utf8');
  }
}

// ── CLI entry: validate-first against the real registry, write to docs/agent-guide/ ──
const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] === __filename) {
  const repoRoot = join(dirname(__filename), '..', '..');
  const registryDir = join(repoRoot, 'docs', 'agent-guide', 'registry');
  const outDir = join(repoRoot, 'docs', 'agent-guide');
  const { validateRegistry } = await import('./validate.mjs');
  const validate = (dir, root) => {
    const { ok, errors } = validateRegistry(dir, root);
    return { ok, errors };
  };
  try {
    writeDocs({ registryDir, outDir, repoRoot, validate });
    console.log('✓ wrote docs/agent-guide/{10-ziele,20-werkzeuge,30-bausteine}.md');
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}
