// scripts/agent-guide/emit-maps.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  escapeCell,
  renderGoalsMap,
  renderToolsMap,
  renderDangerMap,
} from './emit-maps.mjs';

test('escapeCell: pipe is backslash-escaped', () => {
  assert.equal(escapeCell('a | b'), 'a \\| b');
});

test('escapeCell: embedded newline collapses to a single space', () => {
  assert.equal(escapeCell('line one\nline two'), 'line one line two');
  assert.equal(escapeCell('line one\r\nline two'), 'line one line two');
});

test('escapeCell: runs of whitespace around a newline collapse to one space', () => {
  assert.equal(escapeCell('a  \n   b'), 'a b');
});

test('escapeCell: leading/trailing whitespace trimmed', () => {
  assert.equal(escapeCell('   padded   '), 'padded');
});

test('escapeCell: pipe and newline together stay table-safe', () => {
  assert.equal(escapeCell('„Fix |broken|\nlogin“'), '„Fix \\|broken\\| login“');
});

test('escapeCell: empty/undefined renders as the em-dash placeholder', () => {
  assert.equal(escapeCell(''), '—');
  assert.equal(escapeCell(undefined), '—');
  assert.equal(escapeCell(null), '—');
});

// ---- shared fixture builder (in-memory registry, mirrors loadRegistry's return shape) ----
function makeRegistry({ goals = [], tools = [], taxonomy = [], guardrails = [] } = {}) {
  const taxById = new Map(taxonomy.map((t) => [t.id, t]));
  const toolMap = new Map(tools.map((t) => [t.id, t]));
  const grMap = new Map(guardrails.map((g) => [g.id, g]));
  return {
    goals,
    tools,
    taxonomy,
    guardrails,
    components: [],
    tierFor: (id) => taxById.get(id),
    toolById: (id) => toolMap.get(id),
    guardrailById: (id) => grMap.get(id),
  };
}

const FIX_TAXONOMY = [
  { id: 'safe', label_de: 'Sicher', emoji: '🟢', meaning_de: 'Ungefährlich.', enforcement_default: 'allow' },
  { id: 'caution', label_de: 'Vorsicht', emoji: '🟡', meaning_de: 'Mit Bedacht.', enforcement_default: 'warn' },
  { id: 'assisted', label_de: 'Nur mit Hilfe', emoji: '🟠', meaning_de: 'Nur begleitet.', enforcement_default: 'confirm' },
  { id: 'forbidden', label_de: 'Niemals allein', emoji: '🔴', meaning_de: 'Nie allein.', enforcement_default: 'block' },
];

const FIX_GUARDRAILS = [
  { id: 'G-PR-ONLY', name_de: 'Nur per PR' },
  { id: 'G-PULL-FIRST', name_de: 'Erst pullen' },
  { id: 'G-ENV-EXPLICIT', name_de: 'ENV immer explizit' },
];

const FIX_TOOLS = [
  { id: 'dev-flow-execute', name_de: 'Plan ausführen', kind: 'skill', harness: 'claude', summary_de: 'Setzt einen Plan um.', danger: 'caution', guardrails: ['G-PR-ONLY'] },
  { id: 'dev-flow-plan', name_de: 'Plan erstellen', kind: 'skill', harness: 'claude', summary_de: 'Erstellt einen Plan.', danger: 'caution', guardrails: ['G-PULL-FIRST'] },
];

test('renderGoalsMap: header on line 1, sorted rows, flow joined, empty guardrails as dash', () => {
  const reg = makeRegistry({
    taxonomy: FIX_TAXONOMY,
    guardrails: FIX_GUARDRAILS,
    tools: FIX_TOOLS,
    goals: [
      // intentionally out of id order to prove sort-by-id
      { id: 'g-status', title_de: 'Ich will wissen, ob ein Dienst läuft', flow: [], danger: 'safe', guardrails: [], example_prompt_de: '„Läuft Nextcloud?“' },
      { id: 'g-change-text', title_de: 'Ich will den Website-Text ändern', flow: [{ tool: 'dev-flow-plan' }, { tool: 'dev-flow-execute' }], danger: 'caution', guardrails: ['G-PULL-FIRST', 'G-PR-ONLY'], example_prompt_de: '„Ändere den Begrüßungstext.“' },
    ],
  });
  const out = renderGoalsMap(reg);
  const lines = out.split('\n');
  assert.equal(lines[0], '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-maps.mjs; edit the registry -->');
  // sorted by id: g-change-text before g-status
  const idxChange = out.indexOf('Ich will den Website-Text ändern');
  const idxStatus = out.indexOf('Ich will wissen, ob ein Dienst läuft');
  assert.ok(idxChange < idxStatus, 'rows sorted by goal id');
  // flow joined with arrow
  assert.ok(out.includes('dev-flow-plan → dev-flow-execute'), 'flow tool ids joined with arrow');
  // tier emoji + label
  assert.ok(out.includes('🟡 Vorsicht'), 'caution tier rendered');
  assert.ok(out.includes('🟢 Sicher'), 'safe tier rendered');
  // empty guardrails -> dash; non-empty joined by comma-space and sorted by id
  // (input order ['G-PULL-FIRST','G-PR-ONLY'] renders sorted: G-PR-ONLY before G-PULL-FIRST)
  assert.ok(out.includes('G-PR-ONLY, G-PULL-FIRST'), 'guardrail ids joined and sorted by id');
  assert.ok(/\|\s*🟢 Sicher\s*\|\s*—\s*\|/.test(out), 'empty guardrails render as em-dash');
  // single trailing newline, LF only
  assert.ok(out.endsWith('\n'), 'ends with newline');
  assert.ok(!out.endsWith('\n\n'), 'single trailing newline');
  assert.ok(!out.includes('\r'), 'LF line endings only');
});

test('renderGoalsMap: free-text cell with a pipe stays table-safe', () => {
  const reg = makeRegistry({
    taxonomy: FIX_TAXONOMY,
    guardrails: FIX_GUARDRAILS,
    tools: FIX_TOOLS,
    goals: [
      { id: 'g-pipe', title_de: 'Ich will a | b', flow: [{ tool: 'dev-flow-plan' }], danger: 'safe', guardrails: [], example_prompt_de: '„Fix |broken|\nlogin“' },
    ],
  });
  const out = renderGoalsMap(reg);
  assert.ok(out.includes('Ich will a \\| b'), 'pipe in title escaped');
  assert.ok(out.includes('„Fix \\|broken\\| login“'), 'pipe+newline in prompt escaped & collapsed');
  // every table data row has exactly the right number of unescaped pipes (6 borders for 5 columns)
  const dataRow = out.split('\n').find((l) => l.includes('Ich will a \\| b'));
  const unescaped = dataRow.replace(/\\\|/g, '');
  assert.equal((unescaped.match(/\|/g) || []).length, 6, 'row keeps 5 columns intact');
});

test('renderToolsMap: three sections in fixed order Skills/Tasks/Agenten, sorted within', () => {
  const reg = makeRegistry({
    taxonomy: FIX_TAXONOMY,
    guardrails: FIX_GUARDRAILS,
    tools: [
      { id: 'agent-security', name_de: 'Security-Agent', kind: 'agent', harness: 'both', summary_de: 'Secrets & Auth.', danger: 'forbidden', guardrails: ['G-ENV-EXPLICIT'] },
      { id: 'agent-ops', name_de: 'Ops-Agent', kind: 'agent', harness: 'both', summary_de: 'Status & Logs.', danger: 'safe', guardrails: [] },
      { id: 'task-oracle', name_de: 'Task-Orakel', kind: 'task', harness: 'both', summary_de: 'Findet die richtige Task.', danger: 'safe', guardrails: [] },
      { id: 'dev-flow-plan', name_de: 'Plan erstellen', kind: 'skill', harness: 'claude', summary_de: 'Erstellt einen Plan.', danger: 'caution', guardrails: ['G-PULL-FIRST'] },
      { id: 'dev-flow-execute', name_de: 'Plan ausführen', kind: 'skill', harness: 'claude', summary_de: 'Setzt einen Plan um.', danger: 'caution', guardrails: ['G-PR-ONLY'] },
    ],
  });
  const out = renderToolsMap(reg);
  assert.equal(out.split('\n')[0], '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-maps.mjs; edit the registry -->');

  const iSkills = out.indexOf('## Skills');
  const iTasks = out.indexOf('## Tasks');
  const iAgenten = out.indexOf('## Agenten');
  assert.ok(iSkills > -1 && iTasks > -1 && iAgenten > -1, 'all three sections present');
  assert.ok(iSkills < iTasks && iTasks < iAgenten, 'sections in order Skills < Tasks < Agenten');

  // task-oracle lands under Tasks (between iTasks and iAgenten)
  const iOracle = out.indexOf('task-oracle');
  assert.ok(iOracle > iTasks && iOracle < iAgenten, 'task-oracle is in the Tasks section');

  // within Skills, sorted by id: dev-flow-execute before dev-flow-plan
  const iExec = out.indexOf('dev-flow-execute');
  const iPlan = out.indexOf('dev-flow-plan');
  assert.ok(iExec > iSkills && iExec < iTasks, 'dev-flow-execute in Skills section');
  assert.ok(iExec < iPlan, 'skills sorted by id');

  // within Agenten, sorted by id: agent-ops before agent-security
  const iOps = out.indexOf('agent-ops');
  const iSec = out.indexOf('agent-security');
  assert.ok(iOps > iAgenten && iOps < iSec, 'agenten sorted by id');

  // tier + guardrails rendering
  assert.ok(out.includes('🔴 Niemals allein'), 'forbidden tier rendered');
  assert.ok(out.includes('G-ENV-EXPLICIT'), 'tool guardrail id rendered');
  assert.ok(/\|\s*🟢 Sicher\s*\|.*\|\s*—\s*\|/.test(out), 'empty tool guardrails render as em-dash');

  assert.ok(out.endsWith('\n') && !out.endsWith('\n\n'), 'single trailing newline');
  assert.ok(!out.includes('\r'), 'LF only');
});

test('renderDangerMap: 4 tiers in canonical order, transitive guardrail bucketing, de-dup', () => {
  const reg = makeRegistry({
    taxonomy: FIX_TAXONOMY,
    guardrails: [
      { id: 'G-PR-ONLY', name_de: 'Nur per PR' },
      { id: 'G-PULL-FIRST', name_de: 'Erst pullen' },
      { id: 'G-ENV-EXPLICIT', name_de: 'ENV immer explizit' },
      { id: 'G-DUP', name_de: 'Doppelt referenziert' },
    ],
    tools: [
      // a forbidden tool that references G-PULL-FIRST + G-ENV-EXPLICIT
      { id: 'agent-security', name_de: 'Security-Agent', kind: 'agent', summary_de: 'Secrets.', danger: 'forbidden', guardrails: ['G-PULL-FIRST', 'G-ENV-EXPLICIT'] },
    ],
    goals: [
      // caution goal referencing G-PULL-FIRST (so G-PULL-FIRST appears under caution AND forbidden)
      { id: 'g-change', title_de: 'Ich will Text ändern', flow: [], danger: 'caution', guardrails: ['G-PULL-FIRST', 'G-PR-ONLY'], example_prompt_de: 'x' },
      // two caution goals both referencing G-DUP -> de-dup within caution
      { id: 'g-a', title_de: 'A', flow: [], danger: 'caution', guardrails: ['G-DUP'], example_prompt_de: 'x' },
      { id: 'g-b', title_de: 'B', flow: [], danger: 'caution', guardrails: ['G-DUP'], example_prompt_de: 'x' },
      // a safe goal with no guardrails
      { id: 'g-status', title_de: 'Ich will Status', flow: [], danger: 'safe', guardrails: [], example_prompt_de: 'x' },
    ],
  });
  const out = renderDangerMap(reg);
  assert.equal(out.split('\n')[0], '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-maps.mjs; edit the registry -->');

  // canonical tier order
  const iSafe = out.indexOf('🟢 Sicher');
  const iCaution = out.indexOf('🟡 Vorsicht');
  const iAssisted = out.indexOf('🟠 Nur mit Hilfe');
  const iForbidden = out.indexOf('🔴 Niemals allein');
  assert.ok(iSafe < iCaution && iCaution < iAssisted && iAssisted < iForbidden, 'tiers in canonical order');

  // enforcement_default surfaced
  assert.ok(out.includes('enforcement_default'), 'enforcement default labeled');
  assert.ok(out.includes('block'), 'forbidden enforcement_default rendered');

  // helper: slice the section text for a tier (from its heading to the next tier heading or EOF)
  const sliceTier = (label) => {
    const start = out.indexOf(label);
    const nexts = ['🟢 Sicher', '🟡 Vorsicht', '🟠 Nur mit Hilfe', '🔴 Niemals allein']
      .map((l) => out.indexOf(l)).filter((i) => i > start);
    const end = nexts.length ? Math.min(...nexts) : out.length;
    return out.slice(start, end);
  };

  const caution = sliceTier('🟡 Vorsicht');
  const forbidden = sliceTier('🔴 Niemals allein');

  // transitive: G-PULL-FIRST appears under BOTH caution and forbidden
  assert.ok(caution.includes('G-PULL-FIRST'), 'G-PULL-FIRST under caution (via goal)');
  assert.ok(forbidden.includes('G-PULL-FIRST'), 'G-PULL-FIRST under forbidden (via tool)');

  // de-dup: G-DUP appears exactly once within caution
  assert.equal((caution.match(/G-DUP/g) || []).length, 1, 'G-DUP de-duplicated within caution');

  // goals/tools bucketed under their own tier
  assert.ok(caution.includes('g-change') && caution.includes('Ich will Text ändern'), 'caution goal listed');
  assert.ok(forbidden.includes('agent-security'), 'forbidden tool listed');

  // sorted by guardrail id within forbidden: G-ENV-EXPLICIT before G-PULL-FIRST
  assert.ok(forbidden.indexOf('G-ENV-EXPLICIT') < forbidden.indexOf('G-PULL-FIRST'), 'guardrails sorted by id');

  assert.ok(out.endsWith('\n') && !out.endsWith('\n\n'), 'single trailing newline');
  assert.ok(!out.includes('\r'), 'LF only');
});

test('fail-closed: a flow.tool with no tools.yaml entry throws', () => {
  const reg = makeRegistry({
    taxonomy: FIX_TAXONOMY,
    guardrails: FIX_GUARDRAILS,
    tools: [],
    goals: [
      { id: 'g-x', title_de: 'X', flow: [{ tool: 'does-not-exist' }], danger: 'safe', guardrails: [], example_prompt_de: 'x' },
    ],
  });
  assert.throws(() => renderGoalsMap(reg), /flow tool id "does-not-exist" has no tools\.yaml entry/);
});

test('fail-closed: a goal.danger with no taxonomy entry throws', () => {
  const reg = makeRegistry({
    taxonomy: [],
    guardrails: FIX_GUARDRAILS,
    tools: [],
    goals: [
      { id: 'g-x', title_de: 'X', flow: [], danger: 'nonexistent-tier', guardrails: [], example_prompt_de: 'x' },
    ],
  });
  assert.throws(() => renderGoalsMap(reg), /danger id "nonexistent-tier" has no taxonomy entry/);
});

test('fail-closed: a guardrail id with no guardrails.yaml entry throws', () => {
  const reg = makeRegistry({
    taxonomy: FIX_TAXONOMY,
    guardrails: [],
    tools: [],
    goals: [
      { id: 'g-x', title_de: 'X', flow: [], danger: 'safe', guardrails: ['G-MISSING'], example_prompt_de: 'x' },
    ],
  });
  assert.throws(() => renderGoalsMap(reg), /guardrail id "G-MISSING" has no guardrails\.yaml entry/);
});

test('determinism: two separately-constructed registries with different input order render byte-identically', () => {
  // g-b carries MULTIPLE guardrails in a DIFFERENT order between A and B — proves
  // guardrailIds() sorts WITHIN a row, not just that rows are sorted by id.
  const goalsA = [
    { id: 'g-b', title_de: 'B', flow: [{ tool: 'dev-flow-plan' }], danger: 'caution', guardrails: ['G-PULL-FIRST', 'G-ENV-EXPLICIT', 'G-PR-ONLY'], example_prompt_de: 'x' },
    { id: 'g-a', title_de: 'A', flow: [], danger: 'safe', guardrails: [], example_prompt_de: 'y' },
  ];
  // same goals, DIFFERENT row order AND different within-row guardrail order
  const goalsB = [
    { id: 'g-a', title_de: 'A', flow: [], danger: 'safe', guardrails: [], example_prompt_de: 'y' },
    { id: 'g-b', title_de: 'B', flow: [{ tool: 'dev-flow-plan' }], danger: 'caution', guardrails: ['G-PR-ONLY', 'G-PULL-FIRST', 'G-ENV-EXPLICIT'], example_prompt_de: 'x' },
  ];
  const toolsA = [
    { id: 'dev-flow-execute', name_de: 'Plan ausführen', kind: 'skill', harness: 'claude', summary_de: 'Setzt einen Plan um.', danger: 'caution', guardrails: ['G-PR-ONLY', 'G-ENV-EXPLICIT'] },
    { id: 'dev-flow-plan', name_de: 'Plan erstellen', kind: 'skill', harness: 'claude', summary_de: 'Erstellt einen Plan.', danger: 'caution', guardrails: ['G-PULL-FIRST'] },
  ];
  // reversed row order AND reversed within-row guardrail order on dev-flow-execute
  const toolsB = [
    { id: 'dev-flow-plan', name_de: 'Plan erstellen', kind: 'skill', harness: 'claude', summary_de: 'Erstellt einen Plan.', danger: 'caution', guardrails: ['G-PULL-FIRST'] },
    { id: 'dev-flow-execute', name_de: 'Plan ausführen', kind: 'skill', harness: 'claude', summary_de: 'Setzt einen Plan um.', danger: 'caution', guardrails: ['G-ENV-EXPLICIT', 'G-PR-ONLY'] },
  ];
  const regA = makeRegistry({ taxonomy: FIX_TAXONOMY, guardrails: FIX_GUARDRAILS, tools: toolsA, goals: goalsA });
  const regB = makeRegistry({ taxonomy: FIX_TAXONOMY, guardrails: FIX_GUARDRAILS, tools: toolsB, goals: goalsB });
  assert.equal(renderGoalsMap(regA), renderGoalsMap(regB));
  assert.equal(renderToolsMap(regA), renderToolsMap(regB));
  assert.equal(renderDangerMap(regA), renderDangerMap(regB));
});

test('real-shaped taxonomy: label_de already embeds the tier emoji — render must not double-print it', () => {
  // The real registry stores label_de WITH the emoji ("🟡 Vorsicht"); the bare-label fixtures
  // above could not catch a double-print. Pin the strip behaviour against the real shape.
  const realShapedTaxonomy = [
    { id: 'safe', label_de: '🟢 Sicher', emoji: '🟢', meaning_de: 'Ungefährlich.', enforcement_default: 'allow' },
    { id: 'caution', label_de: '🟡 Vorsicht', emoji: '🟡', meaning_de: 'Mit Bedacht.', enforcement_default: 'warn' },
    { id: 'assisted', label_de: '🟠 Nur mit Hilfe', emoji: '🟠', meaning_de: 'Nur begleitet.', enforcement_default: 'confirm' },
    { id: 'forbidden', label_de: '🔴 Niemals allein', emoji: '🔴', meaning_de: 'Nie allein.', enforcement_default: 'block' },
  ];
  const reg = makeRegistry({
    taxonomy: realShapedTaxonomy,
    guardrails: FIX_GUARDRAILS,
    tools: [
      { id: 'agent-security', name_de: 'Security-Agent', kind: 'agent', harness: 'both', summary_de: 'Secrets.', danger: 'forbidden', guardrails: [] },
    ],
    goals: [
      { id: 'g', title_de: 'T', flow: [], danger: 'caution', guardrails: [], example_prompt_de: 'p' },
    ],
  });
  const goals = renderGoalsMap(reg);
  const tools = renderToolsMap(reg);
  const danger = renderDangerMap(reg);
  // single emoji + label, never doubled
  assert.ok(goals.includes('🟡 Vorsicht') && !goals.includes('🟡 🟡'), 'goals tier single emoji');
  assert.ok(tools.includes('🔴 Niemals allein') && !tools.includes('🔴 🔴'), 'tools tier single emoji');
  assert.ok(
    !danger.includes('🟢 🟢') && !danger.includes('🟡 🟡') && !danger.includes('🟠 🟠') && !danger.includes('🔴 🔴'),
    'danger headings single emoji',
  );
});

test('renderToolsMap includes an Init column populated from init_prompt_de', () => {
  const reg = makeRegistry({   // reuse the file's existing fixture builder
    taxonomy: FIX_TAXONOMY,
    guardrails: FIX_GUARDRAILS,
    tools: [{ id: 'dev-flow-plan', name_de: 'Planungs-Skill', kind: 'skill', harness: 'claude',
      danger: 'caution', summary_de: 'Plant.', guardrails: [],
      init_prompt_de: '/dev-flow-plan: plane' }],
  });
  const md = renderToolsMap(reg);
  assert.ok(md.includes('| Id | Name | Art | Harness | Tier | Wofür | Guardrails | Init |'),
    'header must carry the Harness + Init columns');
  assert.ok(md.includes('/dev-flow-plan: plane'), 'init prompt must appear in the row');
  assert.ok(md.includes('claude'), 'harness value must appear in the row');
});

