import { CORRUPT_PERFORMERS_A } from './corrupt-performers-data';
import { CORRUPT_PERFORMERS_B } from './corrupt-performers-data-2';

export const CORRUPT_PERFORMERS: string[] = [
  ...CORRUPT_PERFORMERS_A,
  ...CORRUPT_PERFORMERS_B,
  'zxbkyxvnahrlcl',
  'zxbmyw',
  'zxbmyxrozxjfyw',
  'zxboexjfcv',
  'zxbzaxn',
  'zxhly',
  'zxig',
  'zxiubxa',
  'zxj',
  'zxjfa',
  'zxjfag',
  'zxjfagfszxlfcmvlzf',
  'zxjfagvyx',
  'zxjfc',
  'zxjfd',
  'zxjfdg',
  'zxjfdghhdf',
  'zxjfdglnahrfchvzc',
  'zxjfdhvybnnfmthfsequbxa',
  'zxjflv',
  'zxjfsequbxa',
  'zxjfzm',
  'zxjfznvja',
  'zxjraw',
  'zxjsesbiawxscya',
  'zxjvdgljyv',
  'zxjyywnpywxfy',
  'zxjyywnpywxfzg',
  'zxjzx',
  'zxjzxy',
  'zxnfb',
  'zxnfymlnx',
  'zxnfymxhy',
  'zxnfymzfc',
  'zxnfzmlyc',
  'zxrfchvzc',
  'zxvyx',
  'zxzlbmluz',
  'zyawvuzhnfzgf',
  'zyb',
];
