# Traefik Dynamic Configuration
# Router fuer Domains ohne eigenen Backend-Service.
# Traefik fordert automatisch Let's Encrypt-Zertifikate per DNS-Challenge an.

http:
  middlewares:
    hsts:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

  routers:
    ldap-cert:
      rule: "Host(`bachelorprojekt-ldap.duckdns.org`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: noop@internal
