apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bge-embed-models
spec:
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bge-rerank-models
spec:
  storageClassName: longhorn
