apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website
resources:
  - ../../../k3d/website.yaml
  - ../../../k3d/website-seller-config.yaml
  - website-vars-configmap.yaml
patches:
  - path: image-tag.yaml
    target:
      kind: Deployment
      name: website