apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-config
data:
  MM_DOMAIN: "chat.localhost"
  KC_DOMAIN: "auth.localhost"
  NC_DOMAIN: "files.localhost"
  MEET_DOMAIN: "meet.localhost"
  SIGNALING_DOMAIN: "signaling.localhost"
  COLLABORA_DOMAIN: "office.localhost"
  WHITEBOARD_DOMAIN: "board.localhost"
  VAULT_DOMAIN: "vault.localhost"
  MAIL_DOMAIN: "mail.localhost"
  DOCS_DOMAIN: "docs.localhost"
  GITBOOK_URL: ""
  BILLING_DOMAIN: "billing.localhost"
  WP_DOMAIN: "web.localhost"
  AI_DOMAIN: "ai.localhost"
