apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-config
data:
  MM_DOMAIN: "chat.localhost"
  KC_DOMAIN: "auth.localhost"
  NC_DOMAIN: "files.localhost"
  SIGNALING_DOMAIN: "signaling.localhost"
  COLLABORA_DOMAIN: "office.localhost"
  MAIL_DOMAIN: "mail.localhost"
