apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  labels:
    app: prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - name: prosody
          image: jitsi/prosody:stable-9111
          env:
            - name: XMPP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: domain-config
                  key: JITSI_DOMAIN
            - name: JITSI_XMPP_SUFFIX
              valueFrom:
                configMapKeyRef:
                  name: domain-config
                  key: JITSI_XMPP_SUFFIX
            - name: XMPP_AUTH_DOMAIN
              value: "auth.meet.$(JITSI_XMPP_SUFFIX)"
            - name: XMPP_MUC_DOMAIN
              value: "muc.meet.$(JITSI_XMPP_SUFFIX)"
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: "internal-muc.meet.$(JITSI_XMPP_SUFFIX)"
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homeoffice-secrets
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homeoffice-secrets
                  key: JVB_AUTH_PASSWORD
            - name: ENABLE_AUTH
              value: "1"
            - name: AUTH_TYPE
              value: jwt
            - name: JWT_APP_ID
              value: jitsi
            - name: JWT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: homeoffice-secrets
                  key: JITSI_JWT_SECRET
            - name: JWT_ACCEPTED_ISSUERS
              value: jitsi
            - name: JWT_ACCEPTED_AUDIENCES
              value: jitsi
            - name: JWT_ALLOW_EMPTY
              value: "1"
            - name: ENABLE_GUESTS
              value: "1"
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 5222
            - containerPort: 5347
            - containerPort: 5280
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prosody
spec:
  selector:
    app: prosody
  ports:
    - name: xmpp-client
      port: 5222
      targetPort: 5222
    - name: xmpp-component
      port: 5347
      targetPort: 5347
    - name: bosh
      port: 5280
      targetPort: 5280
