apiVersion: v1
kind: Secret
metadata:
  name: homeoffice-secrets
type: Opaque
stringData:
  KEYCLOAK_DB_PASSWORD: "devkeycloakdb"
  KEYCLOAK_ADMIN_PASSWORD: "devadmin"
  MATTERMOST_DB_PASSWORD: "devmattermostdb"
  MATTERMOST_OIDC_SECRET: "devmattermostoidcsecret12345"
  NEXTCLOUD_OIDC_SECRET: "devnextcloudoidcsecret12345"
  NEXTCLOUD_DB_PASSWORD: "devnextclouddb"
  NEXTCLOUD_ADMIN_PASSWORD: "devnextcloudadmin"
  SIGNALING_SECRET: "devsignalingsecret1234567890abcdef"
  TURN_SECRET: "devturnpassword1234"
  INVOICENINJA_DB_PASSWORD: "devinvoiceninjadb"
  INVOICENINJA_APP_KEY: "base64:ZGV2aW52b2ljZW5pbmphYXBwa2V5MTIzNDU2Nzg="
  INVOICENINJA_ADMIN_PASSWORD: "devinvoiceninja"
  SHARED_DB_PASSWORD: "devshareddb"
