-- 2026-05-08 — Cleanup + grouping backfill for systemtest auto-tickets.
--
-- Symptom: 47 of 48 open tickets on mentolder were generated by
-- failure-bridge.ts with `component`/`parent_id` NULL and (worse)
-- `is_test_data=false`, even though every source assignment was
-- `is_test_data=true` (seeded fixtures). The bridge's idempotency
-- relied on `questionnaire_test_status.last_failure_ticket_id` and
-- silently failed when the row didn't exist or the assignment didn't
-- match — so 47 separate test runs each opened a fresh ticket.
--
-- Compounding: the systemtest seeder clones `questionnaire_templates`
-- and `questionnaire_questions` per assignment (fresh UUIDs), so
-- grouping by `template_id` produces one epic per run. This script
-- groups by **template title slug** instead — stable across re-seeds.
--
-- This script is idempotent. Steps (all in one tx):
--   1. Auto-create one parent epic per (brand, template-title-slug),
--      external_id `EPIC-SYS-<brand>-<slug>`. is_test_data flag set
--      from the worst-case child (any test-data child → epic test-data).
--   2. Hang every existing systemtest ticket under its title-slug epic.
--   3. Backfill `component='systemtest'`, `severity='minor'`, and
--      `is_test_data` (from the source assignment OR the [TEST] title
--      prefix) on all systemtest-sourced rows.
--   4. Archive every is_test_data ticket as `resolution='obsolete'` —
--      seeded test fixtures must not sit in the real triage queue.
--      Real (non-test-data) systemtest tickets stay in 'triage'.
--   5. Repoint `questionnaire_test_status.last_failure_ticket_id` at
--      the canonical surviving ticket per question.

\set ON_ERROR_STOP on
BEGIN;

SELECT set_config('app.user_label', 'cleanup:2026-05-08-tickets-dedup', true);

-- Helper: reusable title-slug expression.
-- LOWER + REGEXP_REPLACE non-alnum→'-', then trim leading/trailing dashes.
-- Mirrors `slugifyTitle` in failure-bridge.ts. Truncated to 80 chars.
-- (Inlined as CTE so we don't pollute the schema with a function.)
WITH title_slugs AS (
  SELECT DISTINCT
         t.brand,
         qt.title AS template_title,
         LEFT(
           TRIM(BOTH '-' FROM
             REGEXP_REPLACE(LOWER(qt.title), '[^a-z0-9]+', '-', 'g')
           ), 80
         ) AS slug,
         BOOL_OR(COALESCE(qa.is_test_data, false) OR qt.title LIKE '%[TEST]%') AS is_test_data
    FROM tickets.tickets t
    JOIN questionnaire_questions qq ON qq.id = t.source_test_question_id
    JOIN questionnaire_templates qt ON qt.id = qq.template_id
    LEFT JOIN questionnaire_assignments qa ON qa.id = t.source_test_assignment_id
   WHERE t.source_test_question_id IS NOT NULL
     AND t.type = 'bug'
   GROUP BY t.brand, qt.title
)
INSERT INTO tickets.tickets
       (external_id, type, brand, title, description, status,
        component, severity, is_test_data)
SELECT 'EPIC-SYS-' || ts.brand || '-' || ts.slug,
       'project',
       ts.brand,
       LEFT('Systemtest: ' || ts.template_title, 200),
       'Auto-erstelltes Epic für alle Systemtest-Fehler aus Template **'
         || ts.template_title || '**.' || E'\n\n'
         || 'Kinder werden vom failure-bridge automatisch eingehängt; '
         || 'geschlossene Tickets werden bei Regressions wiedereröffnet.',
       'in_progress',
       'systemtest',
       'minor',
       ts.is_test_data
  FROM title_slugs ts
ON CONFLICT (external_id) DO UPDATE SET
  is_test_data = tickets.tickets.is_test_data OR EXCLUDED.is_test_data,
  updated_at   = now();

-- 2) Hang every systemtest ticket under its title-slug epic + backfill
--    grouping fields. Pre-compute the epic-id-and-test-flag per ticket
--    in a CTE because PG forbids referencing the UPDATE target in JOIN
--    ON clauses inside the FROM list.
WITH ticket_epic_map AS (
  SELECT t.id    AS ticket_id,
         e.id    AS epic_id,
         (COALESCE(qa.is_test_data, false) OR qt.title LIKE '%[TEST]%') AS test_flag
    FROM tickets.tickets t
    JOIN questionnaire_questions qq ON qq.id = t.source_test_question_id
    JOIN questionnaire_templates qt ON qt.id = qq.template_id
    LEFT JOIN questionnaire_assignments qa ON qa.id = t.source_test_assignment_id
    JOIN tickets.tickets e
      ON e.external_id = 'EPIC-SYS-' || t.brand || '-' ||
         LEFT(TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER(qt.title), '[^a-z0-9]+', '-', 'g')), 80)
   WHERE t.type = 'bug'
     AND t.source_test_question_id IS NOT NULL
)
UPDATE tickets.tickets t
   SET parent_id    = m.epic_id,
       component    = COALESCE(t.component, 'systemtest'),
       severity     = COALESCE(t.severity, 'minor'),
       is_test_data = t.is_test_data OR m.test_flag
  FROM ticket_epic_map m
 WHERE t.id = m.ticket_id;

-- 3) Archive every is_test_data systemtest ticket as resolution='obsolete'.
--    These are seeded fixtures from the failure-loop test suite — they
--    were never real bugs, just signal that the suite ran. Keeping them
--    grouped under their epic for traceability; out of triage forever.
UPDATE tickets.tickets t
   SET status     = 'archived',
       resolution = 'obsolete',
       updated_at = now()
 WHERE t.is_test_data = true
   AND t.type = 'bug'
   AND t.source_test_question_id IS NOT NULL
   AND t.status NOT IN ('done','archived');

-- 4) Repoint questionnaire_test_status.last_failure_ticket_id at any
--    surviving (still open) canonical for the same question. Best-effort
--    — multiple questions may map to one stale row; we just pick one.
UPDATE questionnaire_test_status qts
   SET last_failure_ticket_id = sub.canonical_id
  FROM (
    SELECT DISTINCT ON (t.source_test_question_id)
           t.source_test_question_id AS question_id,
           t.id                       AS canonical_id
      FROM tickets.tickets t
     WHERE t.source_test_question_id IS NOT NULL
       AND t.status NOT IN ('done','archived')
     ORDER BY t.source_test_question_id, t.created_at ASC
  ) sub
 WHERE qts.question_id = sub.question_id
   AND (qts.last_failure_ticket_id IS NULL
        OR qts.last_failure_ticket_id <> sub.canonical_id);

-- Sanity report (NOTICE; doesn't affect commit).
DO $$
DECLARE
  open_total      INT;
  open_real       INT;
  archived_test   INT;
  epics_count     INT;
  open_systemtest INT;
BEGIN
  SELECT COUNT(*) INTO open_total
    FROM tickets.tickets WHERE status NOT IN ('done','archived') AND type='bug';
  SELECT COUNT(*) INTO open_real
    FROM tickets.tickets WHERE status NOT IN ('done','archived') AND type='bug' AND NOT is_test_data;
  SELECT COUNT(*) INTO archived_test
    FROM tickets.tickets WHERE status='archived' AND resolution='obsolete' AND is_test_data;
  SELECT COUNT(*) INTO epics_count
    FROM tickets.tickets WHERE external_id LIKE 'EPIC-SYS-%';
  SELECT COUNT(*) INTO open_systemtest
    FROM tickets.tickets WHERE status NOT IN ('done','archived')
                           AND component='systemtest' AND type='bug';
  RAISE NOTICE 'Post-cleanup: % open bugs total (% real triage, % open systemtest); % epics; % test fixtures archived obsolete',
    open_total, open_real, open_systemtest, epics_count, archived_test;
END $$;

COMMIT;
