apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workspace-coturn
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          workspace: "true"
          workspace-coturn: "true"
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      name: workspace-coturn-{{name}}
    spec:
      destination:
        namespace: coturn
        server: '{{server}}'
      ignoreDifferences:
      - group: ""
        jsonPointers:
        - /data/TURN_SECRET
        - /data/SIGNALING_SECRET
        kind: Secret
        name: coturn-secrets
        namespace: coturn
      project: workspace
      source:
        path: k3d/coturn-stack
        plugin:
          env:
          - name: PROD_DOMAIN
            value: '{{metadata.annotations.workspace-domain}}'
          - name: TURN_PUBLIC_IP
            value: '{{metadata.annotations.workspace-turn-ip}}'
          - name: TURN_NODE
            value: '{{metadata.annotations.workspace-turn-node}}'
          - name: TLS_SECRET_NAME
            value: '{{metadata.annotations.workspace-tls-secret}}'
          name: kustomize-envsubst
        repoURL: https://github.com/Paddione/Bachelorprojekt
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
