apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-config
data:
  MM_DOMAIN: "chat.${PROD_DOMAIN}"
  KC_DOMAIN: "auth.${PROD_DOMAIN}"
  NC_DOMAIN: "files.${PROD_DOMAIN}"
  MEET_DOMAIN: "meet.${PROD_DOMAIN}"
  COLLABORA_DOMAIN: "office.${PROD_DOMAIN}"
  SIGNALING_DOMAIN: "signaling.${PROD_DOMAIN}"
  VAULT_DOMAIN: "vault.${PROD_DOMAIN}"
  MAIL_DOMAIN: "mail.${PROD_DOMAIN}"
  DOCS_DOMAIN: "docs.${PROD_DOMAIN}"
  BILLING_DOMAIN: "billing.${PROD_DOMAIN}"
  WEB_DOMAIN: "web.${PROD_DOMAIN}"
  WIKI_DOMAIN: "wiki.${PROD_DOMAIN}"
  AI_DOMAIN: "ai.${PROD_DOMAIN}"
