apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  template:
    spec:
      containers:
        - name: whisper
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "8"
