apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  template:
    spec:
      containers:
        - name: vaultwarden
          env:
            - name: DOMAIN
              value: "https://vault.${PROD_DOMAIN}"
            - name: SSO_AUTHORITY
              value: "https://auth.${PROD_DOMAIN}/realms/workspace"
            - name: SMTP_HOST
              value: "smtp.mailbox.org"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURITY
              value: "starttls"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: SMTP_PASSWORD
            - name: SMTP_FROM_NAME
              value: "Vaultwarden"
