apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-docs
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          args:
            - "--config=/run/config/oauth2-extra.cfg"
            - "--provider=keycloak-oidc"
            - "--client-id=docs"
            - "--client-secret=$(DOCS_OIDC_SECRET)"
            - "--redirect-url=https://docs.${PROD_DOMAIN}/oauth2/callback"
            - "--oidc-issuer-url=https://auth.${PROD_DOMAIN}/realms/workspace"
            - "--ssl-insecure-skip-verify=true"
            - "--skip-oidc-discovery=true"
            - "--login-url=https://auth.${PROD_DOMAIN}/realms/workspace/protocol/openid-connect/auth"
            - "--redeem-url=http://keycloak:8080/realms/workspace/protocol/openid-connect/token"
            - "--oidc-jwks-url=http://keycloak:8080/realms/workspace/protocol/openid-connect/certs"
            - "--profile-url=http://keycloak:8080/realms/workspace/protocol/openid-connect/userinfo"
            - "--upstream=http://docs:80"
            - "--http-address=0.0.0.0:4180"
            - "--cookie-secure=true"
            - "--cookie-name=_oauth2_proxy_docs"
            - "--email-domain=*"
            - "--pass-access-token=true"
            - "--pass-authorization-header=true"
            - "--set-xauthrequest=true"
            - "--skip-provider-button=true"
            - "--code-challenge-method=S256"
            - "--insecure-oidc-allow-unverified-email=true"
            - "--oidc-extra-audience=docs"
            - "--scope=openid email profile"
          env:
            - name: DOCS_OIDC_SECRET
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: DOCS_OIDC_SECRET
