apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          env:
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: OVERWRITECLIURL
              value: "https://files.${PROD_DOMAIN}"
            - name: OVERWRITEHOST
              value: "files.${PROD_DOMAIN}"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "files.${PROD_DOMAIN} localhost"
            - name: SMTP_HOST
              value: "smtp.mailbox.org"
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_SECURE
              value: "ssl"
            - name: SMTP_AUTHTYPE
              value: "LOGIN"
            - name: SMTP_NAME
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: SMTP_FROM
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workspace-secrets
                  key: SMTP_PASSWORD
            - name: MAIL_FROM_ADDRESS
              value: "nextcloud"
            - name: MAIL_DOMAIN
              value: "${PROD_DOMAIN}"
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: "files.${PROD_DOMAIN}"
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: "files.${PROD_DOMAIN}"
