apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: workspace
spec:
  template:
    spec:
      containers:
        - name: whisper
          image: fedirz/faster-whisper-server:latest-cpu
          imagePullPolicy: Always
