apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
spec:
  template:
    spec:
      containers:
        - name: mattermost
          env:
            - name: MM_SERVICESETTINGS_SITEURL
              value: "https://chat.${PROD_DOMAIN}"
            - name: MM_GITLABSETTINGS_AUTHENDPOINT
              value: "https://auth.${PROD_DOMAIN}/realms/workspace/protocol/openid-connect/auth"
