apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspace-wildcard
  namespace: workspace
spec:
  secretName: ${TLS_SECRET_NAME}
  secretTemplate:
    annotations:
      reflector.v1.emberstack.eu/reflection-allowed: "true"
      reflector.v1.emberstack.eu/reflection-allowed-namespaces: "coturn,workspace-office,website"
      reflector.v1.emberstack.eu/reflection-auto-enabled: "true"
      reflector.v1.emberstack.eu/reflection-auto-namespaces: "coturn,workspace-office,website"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.${PROD_DOMAIN}"
    - "${PROD_DOMAIN}"
