#!/usr/bin/env bats
# FA-AR-01: filter-diff.sh strips noise file sections from a unified diff.
setup() { load 'test_helper.bash'; }

FD="scripts/factory/filter-diff.sh"

# Helper: build a minimal one-file diff section for path $1 with body lines $2..
_section() {
  local path="$1"; shift
  printf 'diff --git a/%s b/%s\n' "$path" "$path"
  printf 'index 0000000..1111111 100644\n'
  printf -- '--- a/%s\n' "$path"
  printf -- '+++ b/%s\n' "$path"
  printf '@@ -1,1 +1,2 @@\n'
  local l
  for l in "$@"; do printf '+%s\n' "$l"; done
}

@test "FA-AR-01: pnpm-lock.yaml section is stripped" {
  run bash "$FD" - <<< "$(_section pnpm-lock.yaml 'resolution stuff')"
  [ "$status" -eq 0 ]
  [[ "$output" != *"pnpm-lock.yaml"* ]]
}

@test "FA-AR-01: go.sum section is stripped" {
  run bash "$FD" - <<< "$(_section go.sum 'h1:abc')"
  [ "$status" -eq 0 ]
  [[ "$output" != *"go.sum"* ]]
}

@test "FA-AR-01: *.min.js section is stripped" {
  run bash "$FD" - <<< "$(_section dist/app.min.js 'var a=1')"
  [ "$status" -eq 0 ]
  [[ "$output" != *"app.min.js"* ]]
}

@test "FA-AR-01: *.map section is stripped" {
  run bash "$FD" - <<< "$(_section dist/app.js.map '{"version":3}')"
  [ "$status" -eq 0 ]
  [[ "$output" != *"app.js.map"* ]]
}

@test "FA-AR-01: generated marker in first 5 lines strips the section" {
  run bash "$FD" - <<< "$(_section src/types.ts '// @generated by codegen' 'export type X = 1')"
  [ "$status" -eq 0 ]
  [[ "$output" != *"src/types.ts"* ]]
}

@test "FA-AR-01: SQL migration with generated marker is NOT stripped" {
  run bash "$FD" - <<< "$(_section migrations/001_init.sql '-- Code generated DO NOT EDIT' 'CREATE TABLE x();')"
  [ "$status" -eq 0 ]
  [[ "$output" == *"migrations/001_init.sql"* ]]
}

@test "FA-AR-01: a normal source file is kept" {
  run bash "$FD" - <<< "$(_section src/app.ts 'const a = 1')"
  [ "$status" -eq 0 ]
  [[ "$output" == *"src/app.ts"* ]]
}

@test "FA-AR-01: mixed diff keeps source and drops lockfile" {
  local diff
  diff="$(_section src/app.ts 'const a = 1')
$(_section pnpm-lock.yaml 'resolution')"
  run bash "$FD" - <<< "$diff"
  [ "$status" -eq 0 ]
  [[ "$output" == *"src/app.ts"* ]]
  [[ "$output" != *"pnpm-lock.yaml"* ]]
}

@test "FA-AR-01: empty input gives empty output, exit 0" {
  run bash "$FD" - <<< ""
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "FA-AR-01: all-noise input gives empty output, exit 0" {
  run bash "$FD" - <<< "$(_section yarn.lock 'foo@1.0.0')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}
