import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const TOKEN_SOURCE = join(REPO_ROOT, 'components', 'website', 'src', 'styles', 'sdlc-leitstand.css');
const ICON_SOURCE_DIR = join(REPO_ROOT, 'components', 'website', 'public', 'cockpit');
const ICON_NAMES = ['health-green.svg', 'health-amber.svg', 'health-red.svg', 'chip-open.svg', 'chip-blocked.svg', 'chip-done.svg'];
const CARDS = join(HERE, 'cards');

/** Replace the content between `<!-- name:start -->` and `<!-- name:end -->`. Idempotent. */
export function injectRegion(html, name, payload) {
  const open = `<!-- ${name}:start -->`;
  const close = `<!-- ${name}:end -->`;
  const i = html.indexOf(open);
  const j = html.indexOf(close);
  if (i === -1 || j === -1 || j < i) {
    throw new Error(`injectRegion: missing region ${name}:start/${name}:end`);
  }
  return html.slice(0, i + open.length) + payload + html.slice(j);
}

/** Verbatim copy of the canonical token CSS → _tokens.css (DRY; no regex extraction). */
export function extractTokens() {
  const css = readFileSync(TOKEN_SOURCE, 'utf8');
  const header = `/* GENERATED by design/leitstand-ds/build.mjs — verbatim copy of\n   components/website/src/styles/sdlc-leitstand.css. Do not edit by hand. */\n`;
  writeFileSync(join(HERE, '_tokens.css'), header + css);
}

/** Copy the cockpit glyph SVGs the cards inline into assets/ (tracked local snapshot). */
export function copyAssets() {
  const to = join(HERE, 'assets', 'icons');
  mkdirSync(to, { recursive: true });
  for (const name of ICON_NAMES) {
    copyFileSync(join(ICON_SOURCE_DIR, name), join(to, name));
  }
}

/** Inline every *.svg in absDir as a labelled grid cell. */
export function svgGrid(absDir) {
  return readdirSync(absDir)
    .filter((n) => n.endsWith('.svg'))
    .sort()
    .map((n) => {
      const svg = readFileSync(join(absDir, n), 'utf8')
        .replace(/<\?xml[^>]*\?>/, '')
        .trim();
      const label = basename(n, '.svg');
      return `<div class="ls-icon-cell">${svg}<span class="cap">${label}</span></div>`;
    })
    .join('\n');
}

/** Assemble one card: inject tokens, shared card css, and the icon grid. */
export function assembleCard(html) {
  const tokens = `<style>\n${readFileSync(join(HERE, '_tokens.css'), 'utf8')}\n</style>`;
  const card = `<style>\n${readFileSync(join(HERE, '_card.css'), 'utf8')}\n</style>`;
  let out = injectRegion(html, 'tokens', tokens);
  out = injectRegion(out, 'card', card);
  if (out.includes('<!-- icons-grid:start -->')) {
    out = injectRegion(out, 'icons-grid', svgGrid(join(HERE, 'assets', 'icons')));
  }
  return out;
}

export async function main() {
  extractTokens();
  copyAssets();
  if (!existsSync(CARDS)) { console.log('no cards/ yet'); return; }
  const files = readdirSync(CARDS).filter((n) => n.endsWith('.html')).sort();
  for (const f of files) {
    const p = join(CARDS, f);
    writeFileSync(p, assembleCard(readFileSync(p, 'utf8')));
  }
  console.log(`assembled ${files.length} card(s)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
