import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKEN_SOURCE = join(__dirname, '../../components/website/src/styles/sdlc-leitstand.css');
const TOKEN_GENERATED = join(__dirname, '_tokens.css');

// The header added by build.mjs
const HEADER_PATTERN = /^\/\* GENERATED by design\/leitstand-ds\/build\.mjs — verbatim copy of\n\s+components\/website\/src\/styles\/sdlc-leitstand\.css\. Do not edit by hand\. \*\/\n?/;

function checkSync() {
  try {
    const sourceCss = readFileSync(TOKEN_SOURCE, 'utf8').trim();
    const generatedCssFull = readFileSync(TOKEN_GENERATED, 'utf8');
    
    // Remove header from generated file
    const generatedCss = generatedCssFull.replace(HEADER_PATTERN, '').trim();

    if (sourceCss === generatedCss) {
      console.log("✓ Design tokens are in sync.");
      process.exit(0);
    } else {
      console.error("✗ Design tokens are STALE!");
      console.error(`Source: ${TOKEN_SOURCE}`);
      console.error(`Generated: ${TOKEN_GENERATED}`);
      console.error("\nPlease run: node design/leitstand-ds/build.mjs");
      process.exit(1);
    }
  } catch (err) {
    console.error(`Error during sync check: ${err.message}`);
    process.exit(1);
  }
}

checkSync();
