apiVersion: v1
kind: Namespace
metadata:
  name: $STAGING_NS
  labels:
    staging: "true"
    staging-id: $STAGING_ID
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
