apiVersion: v1
kind: ConfigMap
metadata:
  name: website-vars
  namespace: flux-system
data:
  WEBSITE_HOST: web.korczewski.de
  WEBSITE_SITE_URL: https://web.korczewski.de
  KEYCLOAK_FRONTEND_URL: https://auth.korczewski.de
  AUTH_EXTERNAL_URL: https://auth.korczewski.de
  NEXTCLOUD_EXTERNAL_URL: https://files.korczewski.de
  DOCS_URL: https://docs.korczewski.de
  VAULT_EXTERNAL_URL: https://vault.korczewski.de
  WHITEBOARD_EXTERNAL_URL: https://board.korczewski.de
  TRAEFIK_EXTERNAL_URL: https://traefik.korczewski.de
  MAIL_EXTERNAL_URL: https://mail.korczewski.de
  BRETT_DOMAIN: brett.korczewski.de
  LIVEKIT_DOMAIN: livekit.korczewski.de
  STREAM_DOMAIN: stream.korczewski.de
  ARENA_WS_URL: wss://arena-ws.korczewski.de
  CONTACT_EMAIL: info@korczewski.de
  CONTACT_NAME: Patrick Korczewski
  CONTACT_CITY: "Wuppertal"
  LEGAL_JOBTITLE: Informatiker
  LEGAL_WEBSITE: korczewski.de
  CLUSTER_ENV: korczewski
  SYSTEMTEST_LOOP_ENABLED: "false"
  LLM_ENABLED: "false"
  LLM_RERANK_ENABLED: "false"
  LLM_ROUTER_URL: http://llm-router.workspace-korczewski.svc.cluster.local:4000
  SMTP_FROM: info@korczewski.de