#!/usr/bin/env bash
# brain-ingest-moc.sh — Generate MOC (Map of Content) pages for Brain Wiki (T002679)
#
# Handelt parent MOCs (aus dem Chunk-Manifest), group sub-MOCs und die
# index.md-Regeneration. Wird aus brain-ingest.sh Phase 2b aufgerufen.
#
# Usage: brain-ingest-moc.sh --brain-repo <path> --chunks <tsv> --state <file>
#
#   --brain-repo   Path to the brain wiki repository
#   --chunks       Chunk manifest TSV (from brain-chunk.sh via brain-ingest.sh)
#   --state        State file path (for slug lookup)
set -euo pipefail

BRAIN_REPO=""
CHUNKS_TSV=""
STATE_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --brain-repo) BRAIN_REPO="${2:?--brain-repo requires a value}"; shift ;;
    --chunks)     CHUNKS_TSV="${2:?--chunks requires a value}"; shift ;;
    --state)      STATE_FILE="${2:?--state requires a value}"; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

[ -n "$BRAIN_REPO" ] || { echo "error: --brain-repo required" >&2; exit 1; }
[ -f "$CHUNKS_TSV" ] || { echo "error: chunks TSV not found: $CHUNKS_TSV" >&2; exit 1; }
[ -f "$STATE_FILE" ] || { echo "error: state file not found: $STATE_FILE" >&2; exit 1; }

echo "=== Phase 2b: MOC Generation ==="

# ── Copy parent MOCs (generated by the chunker, index=0 lines in CHUNKS_TSV) ──
moc_count=0
while IFS=$'\t' read -r src_path chunk_file chunk_slug idx heading; do
  [ "$idx" = "0" ] || continue
  [ -f "$chunk_file" ] || continue

  moc_slug="$chunk_slug"
  moc_dest="$BRAIN_REPO/wiki/${moc_slug}.md"

  # Filter: only keep wikilinks whose target page actually exists
  filtered=""
  while IFS= read -r line; do
    if echo "$line" | grep -q '\[\[.*\]\]'; then
      link_slug="$(echo "$line" | grep -o '\[\[[^]]*\]\]' | sed 's/\[\[//;s/\]\]//')"
      if [ -f "$BRAIN_REPO/wiki/${link_slug}.md" ]; then
        filtered+="$line"$'\n'
      fi
    else
      filtered+="$line"$'\n'
    fi
  done < "$chunk_file"
  printf '%s' "$filtered" > "$moc_dest"

  # Write state entry for the MOC
  (
    flock -x 200
    tmp="$(mktemp)"
    jq --arg k "${src_path}#moc" --arg s "$moc_slug" \
      '.[$k] = {slug:$s, type:"moc", transformed_at:(now | todate)}' \
      "$STATE_FILE" > "$tmp" && mv "$tmp" "$STATE_FILE"
  ) 200>"$STATE_FILE.lock"

  moc_count=$((moc_count + 1))
done < "$CHUNKS_TSV"
echo "Parent MOCs: $moc_count"

# ── Generate sub-MOCs per group ──────────────────────────────────────────
for group in ssot-specs runbooks adr gotchas-footguns agent-guide-maps core-docs health-goals diagrams; do
  pages="$(jq -r --arg g "$group" '
    to_entries[] |
    select(.value.type != null) |
    select(.key | startswith("openspec/") or startswith("docs/") or startswith("CLAUDE") or startswith("AGENTS")) |
    "\(.value.slug)\t\(.key)"
  ' "$STATE_FILE" 2>/dev/null || echo "")"

  if [ -z "$pages" ]; then
    continue
  fi

  page_count="$(echo "$pages" | wc -l)"

  moc_content="---
type: moc
tags: [$group, moc]
status: active
source:: Bachelorprojekt scripts/brain/ingest-sources.yaml
---
# ${group} — Map of Content

${page_count} Seiten aus der Gruppe \`${group}\`.

## Seiten

"

  while IFS=$'\t' read -r page_slug page_path; do
    [ -n "$page_slug" ] || continue
    moc_content+="- [[${page_slug}]] — \`${page_path}\`
"
  done <<< "$pages"

  echo "$moc_content" > "$BRAIN_REPO/wiki/${group}-moc.md"
  echo "  Created ${group}-moc.md ($page_count pages)"
done

# ── Regenerate index-moc.md ──────────────────────────────────────────────
echo "Regenerating index-moc.md..."

existing_pages="$(jq -r '
  to_entries[] |
  select(.value.slug != null) |
  .value.slug
' "$STATE_FILE" 2>/dev/null | sort -u || echo "")"

index_content="---
type: moc
tags: [moc, meta]
status: active
source:: Bachelorprojekt brain-initial-ingest (T001861)
---
# Wiki — Map of Content

Zentraler Hub des brain-Wikis. Max. 2 MOC-Hops zu jeder Seite (G-BRAIN08).

## Meta & Qualität

- [[quality-goals]] — Qualitätsziele G-BRAIN01–11
- [[SCHEMA]] — Verfassung und Konventionen

## Arbeiten mit dem Wiki

- [[usage]] — Seiten anlegen, raw→wiki, log-Pflege
- [[cheatsheet]] — Frontmatter-Templates, Wikilink-Syntax
- [[first-aid]] — Erste Hilfe bei roter CI
- [[llm-workflows]] — LLM-Anreicherung: Prompt-Vorlagen

## Software & Plattform

- [[capabilities]] — Software-Capabilities und Plattform-Fähigkeiten

## SSOT Spezifikationen

- [[ssot-specs-moc]] — OpenSpec SSOT-Spezifikationen

## Runbooks

- [[runbooks-moc]] — Betriebsanleitungen

## Architecture Decision Records

- [[adr-moc]] — Architekturentscheidungen

## Gotchas & Footguns

- [[gotchas-moc]] — Bekannte Fallstricke

## Agent Guide

- [[agent-guide-maps]] — Agent-Oberflächen und Guides

## Core Documentation

- [[core-docs-moc]] — Zentrale Projekt-Dokumentation

"

for page_slug in $existing_pages; do
  if ! echo "$index_content" | grep -q "\[\[$page_slug\]\]"; then
    index_content+="- [[${page_slug}]]
"
  fi
done

echo "$index_content" > "$BRAIN_REPO/index.md"
echo "  Updated index.md"
