#!/usr/bin/env bash
# brain-ingest-moc.sh — Generate MOC (Map of Content) pages for Brain Wiki (T002679)
#
# Handelt parent MOCs (aus dem Chunk-Manifest), group sub-MOCs und die
# index.md-Regeneration. Wird aus brain-ingest.sh Phase 2b aufgerufen.
#
# Usage: brain-ingest-moc.sh --brain-repo <path> --chunks <tsv> --state <file>
#
#   --brain-repo   Path to the brain wiki repository
#   --chunks       Chunk manifest TSV (from brain-chunk.sh via brain-ingest.sh)
#   --state        State file path (for slug lookup)
#   --source-root  Bachelorprojekt source root
#   --manifest     Ingest source manifest
#   --metadata-script Deterministic metadata filter
#   --observed-at / --valid-from Fixed lifecycle time for this ingest run
set -euo pipefail

BRAIN_REPO=""
CHUNKS_TSV=""
STATE_FILE=""
SOURCE_ROOT=""
MANIFEST=""
METADATA_SCRIPT=""
OBSERVED_AT=""
VALID_FROM=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --brain-repo) BRAIN_REPO="${2:?--brain-repo requires a value}"; shift ;;
    --chunks)     CHUNKS_TSV="${2:?--chunks requires a value}"; shift ;;
    --state)      STATE_FILE="${2:?--state requires a value}"; shift ;;
    --source-root) SOURCE_ROOT="${2:?--source-root requires a value}"; shift ;;
    --manifest) MANIFEST="${2:?--manifest requires a value}"; shift ;;
    --metadata-script) METADATA_SCRIPT="${2:?--metadata-script requires a value}"; shift ;;
    --observed-at) OBSERVED_AT="${2:?--observed-at requires a value}"; shift ;;
    --valid-from) VALID_FROM="${2:?--valid-from requires a value}"; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

[ -n "$BRAIN_REPO" ] || { echo "error: --brain-repo required" >&2; exit 1; }
[ -f "$CHUNKS_TSV" ] || { echo "error: chunks TSV not found: $CHUNKS_TSV" >&2; exit 1; }
[ -f "$STATE_FILE" ] || { echo "error: state file not found: $STATE_FILE" >&2; exit 1; }
[ -d "$SOURCE_ROOT" ] || { echo "error: source root not found: $SOURCE_ROOT" >&2; exit 1; }
[ -f "$MANIFEST" ] || { echo "error: manifest not found: $MANIFEST" >&2; exit 1; }
[ -f "$METADATA_SCRIPT" ] || { echo "error: metadata script not found: $METADATA_SCRIPT" >&2; exit 1; }
[ -n "$OBSERVED_AT" ] || { echo "error: --observed-at required" >&2; exit 1; }
[ -n "$VALID_FROM" ] || { echo "error: --valid-from required" >&2; exit 1; }

# shellcheck source=./brain-group-match.sh
source "$(dirname "${BASH_SOURCE[0]}")/brain-group-match.sh"
# shellcheck source=./brain-source-provenance.sh
source "$(dirname "${BASH_SOURCE[0]}")/brain-source-provenance.sh"
brain_group_section_for_manifest "$MANIFEST"
GROUPS_SECTION="$_BRAIN_GROUP_SECTION"

source_kind_for_group() {
  case "$1" in
    ssot-specs) echo openspec ;;
    runbooks) echo runbook ;;
    adr) echo adr ;;
    gotchas-footguns) echo gotcha ;;
    agent-guide-maps) echo agent-guide ;;
    core-docs) echo core-doc ;;
    health-goals) echo health-goal ;;
    diagrams) echo diagram ;;
    github-reviewed) echo github-reviewed ;;
    *) return 1 ;;
  esac
}

write_moc() {
  local content="$1" destination="$2" source_file="$3" source_kind="$4"
  local temporary upstream_revision reviewed_marker reviewed_repo reviewed_pr
  local -a metadata_args
  [ -f "$source_file" ] || { echo "error: MOC source missing: $source_file" >&2; return 1; }
  temporary="$(mktemp "$(dirname "$destination")/.moc.XXXXXX")"
  metadata_args=(--source "$source_file" --source-kind "$source_kind" \
    --observed-at "$OBSERVED_AT" --valid-from "$VALID_FROM")
  if [ "$source_kind" = github-reviewed ]; then
    reviewed_marker="$(brain_source_frontmatter_value "$source_file" source_kind || true)"
    reviewed_repo="$(brain_source_frontmatter_value "$source_file" repository || true)"
    reviewed_pr="$(brain_source_frontmatter_value "$source_file" pull_request || true)"
    if [ "$reviewed_marker" = github-reviewed ] || [ -n "$reviewed_repo" ] || [ -n "$reviewed_pr" ]; then
      upstream_revision="$(brain_source_frontmatter_value "$source_file" upstream_revision || true)"
      [ -n "$upstream_revision" ] || {
        rm -f "$temporary"
        echo "error: PR-derived source lacks frontmatter upstream_revision" >&2
        return 1
      }
      metadata_args+=(--upstream-revision "$upstream_revision")
    fi
  fi
  if ! printf '%s' "$content" | python3 "$METADATA_SCRIPT" "${metadata_args[@]}" > "$temporary"; then
    rm -f "$temporary"
    return 1
  fi
  mv "$temporary" "$destination"
}

echo "=== Phase 2b: MOC Generation ==="

# ── Copy parent MOCs (generated by the chunker, index=0 lines in CHUNKS_TSV) ──
moc_count=0
while IFS=$'\t' read -r src_path chunk_file chunk_slug idx heading; do
  [ "$idx" = "0" ] || continue
  [ -f "$chunk_file" ] || continue

  moc_slug="$chunk_slug"
  moc_dest="$BRAIN_REPO/wiki/${moc_slug}.md"

  # Filter: only keep wikilinks whose target page actually exists
  filtered=""
  while IFS= read -r line; do
    if echo "$line" | grep -q '\[\[.*\]\]'; then
      link_slug="$(echo "$line" | grep -o '\[\[[^]]*\]\]' | sed 's/\[\[//;s/\]\]//')"
      if [ -f "$BRAIN_REPO/wiki/${link_slug}.md" ]; then
        filtered+="$line"$'\n'
      fi
    else
      filtered+="$line"$'\n'
    fi
  done < "$chunk_file"
  brain_group_for "$src_path" "$GROUPS_SECTION" || {
    echo "error: no manifest group for parent MOC source: $src_path" >&2
    exit 1
  }
  parent_group="$_BRAIN_GROUP_OUT"
  source_kind="$(source_kind_for_group "$parent_group")" || exit 1
  write_moc "$filtered" "$moc_dest" "$SOURCE_ROOT/$src_path" "$source_kind"

  # Write state entry for the MOC
  (
    flock -x 200
    tmp="$(mktemp)"
    jq --arg k "${src_path}#moc" --arg s "$moc_slug" --arg g "$parent_group" \
      '.[$k] = {slug:$s, type:"moc", group:$g, transformed_at:(now | todate)}' \
      "$STATE_FILE" > "$tmp" && mv "$tmp" "$STATE_FILE"
  ) 200>"$STATE_FILE.lock"

  moc_count=$((moc_count + 1))
done < "$CHUNKS_TSV"
echo "Parent MOCs: $moc_count"

# ── Generate sub-MOCs per group ──────────────────────────────────────────
for group in ssot-specs runbooks adr gotchas-footguns agent-guide-maps core-docs health-goals diagrams github-reviewed; do
  pages=""
  while IFS=$'\t' read -r page_slug page_path stored_group; do
    [ -n "$page_slug" ] || continue
    page_group="$stored_group"
    if [ -z "$page_group" ] || [ "$page_group" = null ]; then
      source_path="${page_path%%#*}"
      brain_group_for "$source_path" "$GROUPS_SECTION" || continue
      page_group="$_BRAIN_GROUP_OUT"
    fi
    [ "$page_group" = "$group" ] || continue
    pages+="${page_slug}"$'\t'"${page_path}"$'\n'
  done < <(jq -r '
    to_entries | sort_by(.key)[] |
    select(.value.type != null) |
    select(.key | startswith("openspec/") or startswith("docs/") or startswith("CLAUDE") or startswith("AGENTS")) |
    "\(.value.slug)\t\(.key)\t\(.value.group // "")"
  ' "$STATE_FILE" 2>/dev/null || echo "")

  if [ -z "$pages" ]; then
    rm -f "$BRAIN_REPO/wiki/${group}-moc.md"
    continue
  fi

  pages="${pages%$'\n'}"
  page_count="$(printf '%s\n' "$pages" | wc -l)"

  moc_content="---
type: moc
tags: [$group, moc]
status: active
source:: Bachelorprojekt scripts/brain/ingest-sources.yaml
---
# ${group} — Map of Content

${page_count} Seiten aus der Gruppe \`${group}\`.

## Seiten

"

  while IFS=$'\t' read -r page_slug page_path; do
    [ -n "$page_slug" ] || continue
    moc_content+="- [[${page_slug}]] — \`${page_path}\`
"
  done <<< "$pages"

  write_moc "$moc_content" "$BRAIN_REPO/wiki/${group}-moc.md" "$MANIFEST" core-doc
  echo "  Created ${group}-moc.md ($page_count pages)"
done

# ── Regenerate index-moc.md ──────────────────────────────────────────────
echo "Regenerating index-moc.md..."

existing_pages="$(jq -r '
  to_entries[] |
  select(.value.slug != null) |
  .value.slug
' "$STATE_FILE" 2>/dev/null | sort -u || echo "")"

index_content="---
type: moc
tags: [moc, meta]
status: active
source:: Bachelorprojekt scripts/brain/ingest-sources.yaml
---
# Wiki — Map of Content

Zentraler Hub des brain-Wikis. Max. 2 MOC-Hops zu jeder Seite (G-BRAIN08).

## Meta & Qualität

- [[quality-goals]] — Qualitätsziele G-BRAIN01–11
- [[SCHEMA]] — Verfassung und Konventionen

## Arbeiten mit dem Wiki

- [[usage]] — Seiten anlegen, raw→wiki, log-Pflege
- [[cheatsheet]] — Frontmatter-Templates, Wikilink-Syntax
- [[first-aid]] — Erste Hilfe bei roter CI
- [[llm-workflows]] — LLM-Anreicherung: Prompt-Vorlagen

## Software & Plattform

- [[capabilities]] — Software-Capabilities und Plattform-Fähigkeiten

## SSOT Spezifikationen

- [[ssot-specs-moc]] — OpenSpec SSOT-Spezifikationen

## Runbooks

- [[runbooks-moc]] — Betriebsanleitungen

## Architecture Decision Records

- [[adr-moc]] — Architekturentscheidungen

## Gotchas & Footguns

- [[gotchas-moc]] — Bekannte Fallstricke

## Agent Guide

- [[agent-guide-maps]] — Agent-Oberflächen und Guides

## Core Documentation

- [[core-docs-moc]] — Zentrale Projekt-Dokumentation

"

for page_slug in $existing_pages; do
  if ! echo "$index_content" | grep -q "\[\[$page_slug\]\]"; then
    index_content+="- [[${page_slug}]]
"
  fi
done

write_moc "$index_content" "$BRAIN_REPO/index.md" "$MANIFEST" core-doc
echo "  Updated index.md"
