// scripts/toolset/emit-map.mjs
//
// Rendert docs/agent-guide/maps/toolset-map.md aus der Registry. Die Karte ist die
// menschenlesbare Senke; die maschinenlesbare ist scripts/toolset-context.sh. Beide lesen
// dieselbe capabilities.yaml, damit sie nicht auseinanderlaufen können.
import fs from 'node:fs';
import path from 'node:path';
import { loadRegistry, isEnforceable } from './lib/registry.mjs';

const registryPath = process.env.TOOLSET_REGISTRY || path.join(process.cwd(), 'docs', 'agent-guide', 'registry', 'capabilities.yaml');
const mapPath = path.join(process.cwd(), 'docs', 'agent-guide', 'maps', 'toolset-map.md');

const registry = loadRegistry(registryPath);

// Die Karte wird generiert; ohne diesen Kopf ginge eine Handänderung beim nächsten Lauf
// wortlos verloren. Gleiche Formulierung wie in docs/agent-guide/maps/tools-map.md.
let md = `<!-- DO NOT EDIT — generated by scripts/toolset/emit-map.mjs; edit docs/agent-guide/registry/capabilities.yaml -->\n\n`;
md += `# Toolset Map — Fähigkeit & Instanzen\n\n`;
md += `_Generiert aus \`docs/agent-guide/registry/capabilities.yaml\`._\n\n`;
md += `Diese Karte ist die menschenlesbare Sicht auf die Kuration. Den rollengefilterten Block\n`;
md += `für einen Agent-Prompt liefert \`bash scripts/toolset-context.sh <rolle>\`.\n\n`;

const residual = [];

for (const [capName, instances] of Object.entries(registry.capabilities)) {
  md += `## Fähigkeit: \`${capName}\`\n\n`;
  for (const [instKey, cfg] of Object.entries(instances)) {
    const tier = cfg.tier ? ` · Tier \`${cfg.tier}\`` : '';
    md += `- **\`${instKey}\`** — Status \`${cfg.state}\`${tier}\n`;
    if (cfg.reason)     md += `  - _Grund:_ ${cfg.reason}\n`;
    if (cfg.use_when)   md += `  - _Wann:_ ${cfg.use_when}\n`;
    if (cfg.avoid_when) md += `  - _Nicht:_ ${cfg.avoid_when}\n`;
    if (cfg.fallback)   md += `  - _Fallback:_ \`${cfg.fallback}\`\n`;
    if (Array.isArray(cfg.roles) && cfg.roles.length > 0) {
      md += `  - _Rollen:_ ${cfg.roles.map(r => `\`${r}\``).join(', ')}\n`;
    }
    if (cfg.deep_ref)   md += `  - _Tiefe:_ \`${cfg.deep_ref}\`\n`;

    // Residuale Mehrdeutigkeit: unreviewed, oder suppressed bei einem Kind, dessen
    // Unterdrückung sync.mjs technisch nicht durchsetzen kann (cli:, agent:).
    if (cfg.state === 'unreviewed') {
      residual.push({ capName, instKey, why: 'unreviewed — noch nicht kuriert' });
    } else if (cfg.state === 'suppressed' && !isEnforceable(instKey)) {
      residual.push({ capName, instKey, why: 'suppressed, aber technisch nicht durchsetzbar' });
    }
  }
  md += `\n`;
}

md += `## Residuale Mehrdeutigkeiten\n\n`;
if (residual.length === 0) {
  md += `Keine — jede Instanz ist kuriert, und jede unterdrückte Instanz ist technisch durchsetzbar.\n`;
} else {
  md += `Diese Einträge sind bewusst offen. Auflösung über den Skill \`toolset-curate\`.\n\n`;
  for (const r of residual) {
    md += `- \`${r.instKey}\` (Fähigkeit \`${r.capName}\`) — ${r.why}\n`;
  }
  md += `\n`;
}

fs.mkdirSync(path.dirname(mapPath), { recursive: true });
fs.writeFileSync(mapPath, md);
console.log(`Generated map at ${mapPath}`);
