apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - image-update-automation.yaml
  - vars-configmap.yaml
  - website-vars-configmap.yaml
  - website.yaml
  - workspace.yaml
patches:
  - path: flux-system/node-affinity-patch.yaml
    target:
      kind: Deployment
      namespace: flux-system
      labelSelector: "app.kubernetes.io/part-of=flux"
