#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# gh-sync.sh — Sync test results to GitHub Issues
# ═══════════════════════════════════════════════════════════════════
# Usage: ./scripts/tracking/gh-sync.sh <results.json>
#
# For each requirement in the test results:
#   1. Finds the matching GitHub issue by title prefix [FA-01]
#   2. Posts a comment with test results
#   3. Updates labels (status:pass / status:fail, current stage)
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

JSON_FILE="${1:?Usage: $0 <results.json>}"
if [[ ! -f "$JSON_FILE" ]]; then
  echo "Error: File not found: ${JSON_FILE}" >&2
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "Error: gh CLI required" >&2
  exit 1
fi

tier=$(jq -r '.meta.tier' "$JSON_FILE")
run_date=$(jq -r '.meta.date' "$JSON_FILE")
total=$(jq -r '.summary.total' "$JSON_FILE")
pass=$(jq -r '.summary.pass' "$JSON_FILE")
fail=$(jq -r '.summary.fail' "$JSON_FILE")

echo "Syncing ${tier} results (${run_date}) to GitHub Issues..."

# ── Get unique requirement IDs from results ──────────────────────
req_ids=$(jq -r '[.results[].req] | unique | .[]' "$JSON_FILE")

for req_id in $req_ids; do
  # Find the issue
  issue_number=$(gh issue list --search "\"[${req_id}]\" in:title" --json number --jq '.[0].number' 2>/dev/null || echo "")
  if [[ -z "$issue_number" ]]; then
    echo "  ${req_id}: no matching issue found, skipping"
    continue
  fi

  # Build results table for this requirement
  results_table=$(jq -r --arg req "$req_id" '
    .results[] | select(.req == $req) |
    "| \(.test) | \(.desc) | \(if .status == "pass" then "✅" elif .status == "fail" then "❌" else "⊘" end) | \(.duration_ms)ms |"
  ' "$JSON_FILE")

  req_pass=$(jq --arg req "$req_id" '[.results[] | select(.req == $req and .status == "pass")] | length' "$JSON_FILE")
  req_fail=$(jq --arg req "$req_id" '[.results[] | select(.req == $req and .status == "fail")] | length' "$JSON_FILE")
  req_total=$(jq --arg req "$req_id" '[.results[] | select(.req == $req)] | length' "$JSON_FILE")

  overall="✅ ALL PASS"
  new_status_label="status:pass"
  [[ "$req_fail" -gt 0 ]] && overall="❌ ${req_fail}/${req_total} FAILED" && new_status_label="status:fail"

  comment_body=$(cat <<EOF
## Test Results — ${tier} tier (${run_date%%T*})

**${overall}** (${req_pass} pass, ${req_fail} fail of ${req_total})

| Test | Description | Status | Duration |
|------|-------------|--------|----------|
${results_table}

<sub>Auto-generated by tracking pipeline</sub>
EOF
)

  # Post comment
  gh issue comment "$issue_number" --body "$comment_body" 2>/dev/null
  echo "  ${req_id} (#${issue_number}): commented (${overall})"

  # Update labels
  gh issue edit "$issue_number" --remove-label "status:pass" --remove-label "status:fail" --remove-label "status:pending" 2>/dev/null || true
  gh issue edit "$issue_number" --add-label "$new_status_label" 2>/dev/null || true

  # If all pass, move stage label to testing
  if [[ "$req_fail" -eq 0 ]]; then
    gh issue edit "$issue_number" \
      --remove-label "stage:idea" \
      --remove-label "stage:implementation" 2>/dev/null || true
    gh issue edit "$issue_number" --add-label "stage:testing" 2>/dev/null || true
  fi
done

echo ""
echo "Sync complete. View issues: gh issue list --label 'status:fail'"
