// scripts/docs-gen/build-smoke.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { runBuild } from '../build-docs.mjs';

/** Build a minimal fixture repo tree and return its root. */
function makeFixtureRepo() {
  const root = mkdtempSync(join(tmpdir(), 'docs-gen-smoke-'));

  // Minimal CLAUDE.md with a routing table the orchestrator reads for domains/edges.
  writeFileSync(join(root, 'CLAUDE.md'), [
    '# CLAUDE.md',
    '',
    '## Agent Routing',
    '',
    '| Signals | Agent |',
    '|---------|-------|',
    '| `website/`, Astro, component | `bachelorprojekt-website` |',
    '| pod, logs, kubectl, status | `bachelorprojekt-ops` |',
    '',
  ].join('\n'), 'utf8');

  // Repo skills: .claude/skills/<name>/SKILL.md
  mkdirSync(join(root, '.claude', 'skills', 'alpha-skill'), { recursive: true });
  writeFileSync(join(root, '.claude', 'skills', 'alpha-skill', 'SKILL.md'), [
    '---',
    'name: alpha-skill',
    'description: First fixture skill.',
    '---',
    '# Alpha Skill',
    '',
    'Alpha body. See [[beta-skill]] for more.',
    '',
  ].join('\n'), 'utf8');

  mkdirSync(join(root, '.claude', 'skills', 'beta-skill'), { recursive: true });
  writeFileSync(join(root, '.claude', 'skills', 'beta-skill', 'SKILL.md'), [
    '---',
    'name: beta-skill',
    'description: Second fixture skill.',
    '---',
    '# Beta Skill',
    '',
    'Beta body.',
    '',
  ].join('\n'), 'utf8');

  // Repo agent: .claude/agents/<name>.md with a block-scalar description.
  mkdirSync(join(root, '.claude', 'agents'), { recursive: true });
  writeFileSync(join(root, '.claude', 'agents', 'bachelorprojekt-ops.md'), [
    '---',
    'name: bachelorprojekt-ops',
    'description: >',
    '  Ops agent for pods, logs, status, restarts and',
    '  general cluster health questions.',
    '---',
    '# Ops Agent',
    '',
    'Ops agent body.',
    '',
  ].join('\n'), 'utf8');

  writeFileSync(join(root, '.claude', 'agents', 'bachelorprojekt-website.md'), [
    '---',
    'name: bachelorprojekt-website',
    'description: Website agent for the homepage, brand and UI.',
    '---',
    '# Website Agent',
    '',
    'Website agent body.',
    '',
  ].join('\n'), 'utf8');

  // Docs markdown: docs/**/*.md
  mkdirSync(join(root, 'docs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'intro.md'), [
    '# Intro',
    '',
    'Intro doc body with a mermaid diagram.',
    '',
    '```mermaid',
    'flowchart LR',
    '  A --> B',
    '```',
    '',
  ].join('\n'), 'utf8');

  // Agent-guide pages (S1): one hand-authored landing + three "generated" stubs.
  mkdirSync(join(root, 'docs', 'agent-guide'), { recursive: true });
  writeFileSync(join(root, 'docs', 'agent-guide', '00-anleitung.md'), [
    '---',
    'title: "Was will ich tun?"',
    'domain: general',
    '---',
    '# Was will ich tun?',
    '',
    'Drei Linsen: [[10-ziele]], [[20-werkzeuge]], [[30-bausteine]].',
    'Und der Website-Agent: [[bachelorprojekt-website]].',
    '',
  ].join('\n'), 'utf8');
  // 10-ziele has ≥2 H2 headings (TOC trigger) and a ```text prompt (Copy button).
  writeFileSync(join(root, 'docs', 'agent-guide', '10-ziele.md'), [
    '---',
    'title: "Ziele"',
    'domain: general',
    'generated_by: scripts/agent-guide/emit-docs.mjs',
    '---',
    '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-docs.mjs -->',
    '# Ziele',
    '',
    'Zurück: [[00-anleitung]].',
    '',
    '## Ich will den Text der Website ändern',
    '',
    '**Diesen Prompt kannst du der KI geben:**',
    '',
    '```text',
    'Ändere den Preis von 90 auf 120.',
    '```',
    '',
    '## Ich will einen Fehler beheben',
    '',
    'Mehr dazu im Werkzeug-Katalog.',
    '',
  ].join('\n'), 'utf8');
  for (const [slug, title] of [
    ['20-werkzeuge', 'Werkzeuge'],
    ['30-bausteine', 'Bausteine'],
  ]) {
    writeFileSync(join(root, 'docs', 'agent-guide', `${slug}.md`), [
      '---',
      `title: "${title}"`,
      'domain: general',
      'generated_by: scripts/agent-guide/emit-docs.mjs',
      '---',
      '<!-- DO NOT EDIT — generated by scripts/agent-guide/emit-docs.mjs -->',
      `# ${title}`,
      '',
      'Zurück: [[00-anleitung]].',
      '',
    ].join('\n'), 'utf8');
  }

  // Legacy HTML: docs/legacy-html/<slug>.html
  mkdirSync(join(root, 'docs', 'legacy-html'), { recursive: true });
  writeFileSync(join(root, 'docs', 'legacy-html', 'architecture.html'), [
    '<!DOCTYPE html>',
    '<html lang="de"><head><title>Architecture — Workspace MVP</title></head>',
    '<body><main class="content"><h1>Architecture</h1><p>Legacy architecture page.</p></main></body>',
    '</html>',
  ].join('\n'), 'utf8');

  return root;
}

test('runBuild: produces the static output contract from a fixture repo', async () => {
  const repoRoot = makeFixtureRepo();
  const outDir = mkdtempSync(join(tmpdir(), 'docs-gen-out-'));
  const pluginsRoot = join(repoRoot, '__no_plugins_here__'); // absent → plugin sources skipped

  try {
    const report = await runBuild({ repoRoot, pluginsRoot, outDir });

    // Landing + section indexes.
    assert.ok(existsSync(join(outDir, 'index.html')), 'index.html written');
    assert.ok(existsSync(join(outDir, 'skills.html')), 'skills.html written');
    assert.ok(existsSync(join(outDir, 'agents.html')), 'agents.html written');
    assert.ok(existsSync(join(outDir, 'docs.html')), 'docs.html written');

    // At least one skill page and one agent page (under their subdirs).
    const skillPages = readdirSync(join(outDir, 'skills')).filter((f) => f.endsWith('.html'));
    assert.ok(skillPages.length >= 1, 'at least one skills/<x>.html written');
    const agentPages = readdirSync(join(outDir, 'agents')).filter((f) => f.endsWith('.html'));
    assert.ok(agentPages.length >= 1, 'at least one agents/<x>.html written');

    // Legacy rewrapped page keeps its bare slug URL.
    assert.ok(existsSync(join(outDir, 'architecture.html')), 'legacy architecture.html written at bare slug');

    // Assets.
    assert.ok(existsSync(join(outDir, 'style.css')), 'style.css written');
    assert.ok(existsSync(join(outDir, 'app.js')), 'app.js written');

    // search.json shape.
    assert.ok(existsSync(join(outDir, 'search.json')), 'search.json written');
    const idx = JSON.parse(readFileSync(join(outDir, 'search.json'), 'utf8'));
    assert.ok(Array.isArray(idx), 'search.json is an array');
    assert.ok(idx.length >= 1, 'search.json is non-empty');
    for (const entry of idx) {
      assert.equal(typeof entry.slug, 'string', 'entry.slug is a string');
      assert.equal(typeof entry.title, 'string', 'entry.title is a string');
      assert.equal(typeof entry.excerpt, 'string', 'entry.excerpt is a string');
    }

    // Build report is returned with counts.
    assert.equal(typeof report, 'object', 'report returned');
    assert.equal(typeof report.counts, 'object', 'report.counts present');
  } finally {
    rmSync(repoRoot, { recursive: true, force: true });
    rmSync(outDir, { recursive: true, force: true });
  }
});

test('runBuild: agent-guide pages discovered, domain general, wikilinks + TOC/copy', async () => {
  const repoRoot = makeFixtureRepo();
  const outDir = mkdtempSync(join(tmpdir(), 'docs-gen-ag-out-'));
  const pluginsRoot = join(repoRoot, '__no_plugins_here__');
  try {
    const report = await runBuild({ repoRoot, pluginsRoot, outDir });

    // (1) discovered + rendered to <slug>.html at bare slug
    for (const slug of ['00-anleitung', '10-ziele', '20-werkzeuge', '30-bausteine']) {
      assert.ok(existsSync(join(outDir, `${slug}.html`)), `${slug}.html rendered`);
    }

    // (2) the [[10-ziele]] wikilink in 00-anleitung.md rewrites to ./10-ziele.html
    const landing = readFileSync(join(outDir, '00-anleitung.html'), 'utf8');
    assert.ok(landing.includes('href="./10-ziele.html"'), '[[10-ziele]] resolved');

    // (3) the agent wikilink resolves to the discovered agent page (subdir slug)
    assert.ok(
      landing.includes('href="./agents/bachelorprojekt-website.html"'),
      '[[bachelorprojekt-website]] resolved to the agent page',
    );

    // (4) none of these refs are in the unresolved report list ({from,ref} pairs)
    const unresolvedRefs = report.unresolved.map((u) => u.ref);
    for (const ref of ['10-ziele', '20-werkzeuge', '30-bausteine', '00-anleitung', 'bachelorprojekt-website']) {
      assert.ok(!unresolvedRefs.includes(ref), `${ref} is NOT unresolved`);
    }

    // (5) spec §6 affordances: the ```text prompt block gets a Copy button …
    const ziele = readFileSync(join(outDir, '10-ziele.html'), 'utf8');
    assert.ok(/copy-btn|copy-button|data-copy/i.test(ziele), 'prompt block got a Copy button');
    // … and the ≥2-H2 page gets an on-page TOC ("Auf dieser Seite").
    assert.ok(/auto-toc|Auf dieser Seite/i.test(ziele), '≥2 H2 → on-page TOC rendered');
  } finally {
    rmSync(repoRoot, { recursive: true, force: true });
    rmSync(outDir, { recursive: true, force: true });
  }
});

// Phase 5.1: search-index.json smoke
test('runBuild: search-index.json exists, has body tokens, is ≤ 2 MB', async () => {
  const repoRoot = makeFixtureRepo();
  const outDir = mkdtempSync(join(tmpdir(), 'docs-gen-idx-out-'));
  const pluginsRoot = join(repoRoot, '__no_plugins_here__');
  try {
    await runBuild({ repoRoot, pluginsRoot, outDir });

    // File must exist.
    const idxPath = join(outDir, 'search-index.json');
    assert.ok(existsSync(idxPath), 'search-index.json written');

    // Must be ≤ 2 MB (2 097 152 bytes).
    const raw = readFileSync(idxPath, 'utf8');
    const byteLen = Buffer.byteLength(raw, 'utf8');
    assert.ok(byteLen <= 2 * 1024 * 1024, `search-index.json size ${byteLen} ≤ 2 MB`);

    // Schema validation: { pages: [...], index: {...} }
    const idx = JSON.parse(raw);
    assert.ok(Array.isArray(idx.pages), 'idx.pages is an array');
    assert.ok(typeof idx.index === 'object' && idx.index !== null, 'idx.index is an object');
    assert.ok(idx.pages.length >= 1, 'at least one page entry');

    // Each page entry must have slug, title, sectionPath, outRelPath.
    for (const p of idx.pages) {
      assert.equal(typeof p.slug, 'string', 'page.slug is string');
      assert.equal(typeof p.title, 'string', 'page.title is string');
      assert.equal(typeof p.sectionPath, 'string', 'page.sectionPath is string');
      assert.equal(typeof p.outRelPath, 'string', 'page.outRelPath is string');
    }

    // Each postings array must contain objects with slug + weight.
    let checked = 0;
    for (const [token, postings] of Object.entries(idx.index)) {
      assert.equal(typeof token, 'string', 'token is a string');
      assert.ok(Array.isArray(postings), `postings for "${token}" is an array`);
      for (const p of postings) {
        assert.equal(typeof p.slug, 'string', 'posting.slug is string');
        assert.equal(typeof p.weight, 'number', 'posting.weight is number');
      }
      if (++checked >= 5) break; // Spot-check first 5 tokens.
    }

    // The fixture fixture skill body contains "alpha" → must appear in index.
    assert.ok('alpha' in idx.index, '"alpha" token indexed from fixture skill body');
  } finally {
    rmSync(repoRoot, { recursive: true, force: true });
    rmSync(outDir, { recursive: true, force: true });
  }
});

// Phase 5.1 (h3-TOC): render-markdown h3 smoke
test('renderMarkdown: h3 headings get ids and appear in TOC alongside h2', async () => {
  const { renderMarkdown } = await import('./render-markdown.mjs');
  const md = [
    '# Haupttitel',
    '',
    '## Abschnitt Eins',
    '',
    'Text hier.',
    '',
    '### Unterabschnitt',
    '',
    'Untertext.',
    '',
    '## Abschnitt Zwei',
    '',
    'Mehr Text.',
    '',
  ].join('\n');
  const result = renderMarkdown(md, {});
  // h2 headings must have ids
  assert.ok(result.html.includes('id="abschnitt-eins"'), 'h2 gets id');
  // h3 heading must have an id (Phase 3.1)
  assert.ok(result.html.includes('id="unterabschnitt"'), 'h3 gets id');
  // TOC must be present (≥2 h2)
  assert.ok(result.html.includes('auto-toc'), 'TOC box present');
  // TOC must reference h3 (with toc-item--h3 class)
  assert.ok(result.html.includes('toc-item--h3') || result.html.includes('#unterabschnitt'), 'h3 in TOC');
});
