# WireGuard config for Hetzner node
# Generated by: scripts/setup-wireguard.sh
# ${NODE_NAME} (${NODE_IP})
[Interface]
PrivateKey = ${NODE_PRIVATE_KEY}
Address = ${NODE_WG_IP}/32
ListenPort = 51820

[Peer]
# WSL2 GPU Workstation
PublicKey = ${WS_PUBLIC_KEY}
AllowedIPs = 10.13.13.2/32
