# WireGuard config for WSL2 GPU workstation
# Generated by: scripts/setup-wireguard.sh
# Variables: WS_PRIVATE_KEY, WS_ADDRESS, NODE{1,2,3}_{PUBLIC_KEY,IP,MESH_IP}
[Interface]
PrivateKey = ${WS_PRIVATE_KEY}
Address = ${WS_ADDRESS}

[Peer]
# Node 1
PublicKey = ${NODE1_PUBLIC_KEY}
Endpoint = ${NODE1_IP}:51820
AllowedIPs = ${NODE1_MESH_IP}/32
PersistentKeepalive = 25

[Peer]
# Node 2
PublicKey = ${NODE2_PUBLIC_KEY}
Endpoint = ${NODE2_IP}:51820
AllowedIPs = ${NODE2_MESH_IP}/32
PersistentKeepalive = 25

[Peer]
# Node 3
PublicKey = ${NODE3_PUBLIC_KEY}
Endpoint = ${NODE3_IP}:51820
AllowedIPs = ${NODE3_MESH_IP}/32
PersistentKeepalive = 25
