# WireGuard config for WSL2 GPU workstation
# Generated by: scripts/setup-wireguard.sh
[Interface]
PrivateKey = ${WS_PRIVATE_KEY}
Address = 10.13.13.2/32

[Peer]
# Hetzner Node 1 (gekko-hetzner-2)
PublicKey = ${NODE1_PUBLIC_KEY}
Endpoint = 178.104.169.206:51820
AllowedIPs = 10.13.13.1/32
PersistentKeepalive = 25

[Peer]
# Hetzner Node 2 (gekko-hetzner-3)
PublicKey = ${NODE2_PUBLIC_KEY}
Endpoint = 46.225.125.59:51820
AllowedIPs = 10.13.13.3/32
PersistentKeepalive = 25

[Peer]
# Hetzner Node 3 (gekko-hetzner-4)
PublicKey = ${NODE3_PUBLIC_KEY}
Endpoint = 178.104.159.79:51820
AllowedIPs = 10.13.13.4/32
PersistentKeepalive = 25
