apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
spec:
  template:
    spec:
      containers:
        - name: collabora
          env:
            - name: server_name
              value: "office.korczewski.de"
