- op: replace
  path: /spec/ingressClassName
  value: traefik
- op: replace
  path: /spec/rules/0/host
  value: auth.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/1/host
  value: chat.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/2/host
  value: files.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/3/host
  value: office.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/4/host
  value: board.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/5/host
  value: signaling.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/6/host
  value: mail.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/7/host
  value: docs.${PROD_DOMAIN}
- op: replace
  path: /spec/rules/8/host
  value: vault.${PROD_DOMAIN}
- op: remove
  path: /spec/rules/9
