- op: replace
  path: /spec/ingressClassName
  value: traefik
- op: replace
  path: /spec/rules/0/host
  value: auth-wbhprojekt.ipv64.de
- op: replace
  path: /spec/rules/1/host
  value: chat-wbhprojekt.ipv64.de
- op: replace
  path: /spec/rules/2/host
  value: files-wbhprojekt.ipv64.de
- op: replace
  path: /spec/rules/3/host
  value: office-wbhprojekt.ipv64.de
- op: replace
  path: /spec/rules/4/host
  value: signaling-wbhprojekt.ipv64.de
- op: replace
  path: /spec/rules/5/host
  value: mail-wbhprojekt.ipv64.de
- op: replace
  path: /spec/rules/6/host
  value: docs-wbhprojekt.ipv64.de
