apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-db-pvc
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  storageClassName: local-path
