// tests/e2e/specs/brett-mentolder-auth-setup.spec.ts
//
// Runs in the `brett-mentolder-setup` project — authenticates against
// brett.mentolder.de (behind oauth2-proxy) via Pocket ID OIDC.
//
// Env vars:
//   BRETT_URL          (default: https://brett.mentolder.de)
//   E2E_ADMIN_USER     (default: paddione)
//   POCKET_ID_OTAC_URL (pre-created login URL; CI without kubectl access)
//
// Login mechanism (T003163): Pocket ID has no password form. The setup logs in
// via a one-time access code generated by the `one-time-access-token` CLI
// (kubectl exec into the pocket-id pod) — see ../lib/oidc.ts. When neither
// kubectl nor POCKET_ID_OTAC_URL is available, the setup marks itself fixme
// fail-closed so the dependent `brett-mentolder` project is skipped rather than
// run without a session (T002199).

import { test as setup } from '@playwright/test';
import * as path from 'path';
import * as fs from 'fs';
import { oidcLoginAvailable, loginViaOIDC } from '../lib/oidc';
import { assertReachable } from '../lib/health-assertions';

const BRETT_URL = (process.env.BRETT_URL ?? 'https://brett.mentolder.de').replace(/\/$/, '');

const AUTH_DIR    = path.join(__dirname, '..', '.auth');
const ADMIN_STATE = path.join(AUTH_DIR, 'mentolder-brett.json');

function ensureAuthDir(): void {
  if (!fs.existsSync(AUTH_DIR)) fs.mkdirSync(AUTH_DIR, { recursive: true });
}

// OIDC login + oauth2-proxy roundtrip easily exceeds the default 10s test
// timeout (observed: Pocket ID SPA redirects take ~10-20s).
setup.setTimeout(120_000);

setup('authenticate mentolder brett admin', async ({ page, request }, testInfo) => {
  ensureAuthDir();

  // Verify brett health endpoint is reachable before login
  await assertReachable(request, `${BRETT_URL}/healthz`, { label: 'brett healthz' }, testInfo);

  if (!oidcLoginAvailable()) {
    // Fail-closed (T002199): never leave the dependent project to run without
    // a session. fixme records the unsupported state visibly instead of a
    // silent early return.
    testInfo.fixme(true, 'OIDC login unavailable — need kubectl (fleet context) or POCKET_ID_OTAC_URL');
    fs.writeFileSync(ADMIN_STATE, JSON.stringify({ cookies: [], origins: [] }));
    console.log('[brett-mentolder-setup] fixme — OIDC login mechanism unavailable');
    return;
  }

  // 1. Pocket ID session via one-time access code.
  await loginViaOIDC(page, { redirect: '/settings' });

  // 2. Drive the oauth2-proxy OIDC flow: brett → oauth2-proxy → Pocket ID
  //    /authorize (already authenticated) → back to brett.
  await page.goto(BRETT_URL, { waitUntil: 'domcontentloaded', timeout: 30_000 });
  await page.waitForURL(new RegExp(`^${BRETT_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`), { timeout: 60_000 });

  // 3. Persist the session so the `brett-mentolder` project can reuse it.
  await page.context().storageState({ path: ADMIN_STATE });
  console.log(`[brett-mentolder-setup] brett admin session saved → ${ADMIN_STATE}`);
});
