import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const BRAND = join(HERE, '..', 'website', 'public', 'brand', 'mentolder');
const CARDS = join(HERE, 'cards');

/** Replace the content between `<!-- name:start -->` and `<!-- name:end -->`. Idempotent. */
export function injectRegion(html, name, payload) {
  const open = `<!-- ${name}:start -->`;
  const close = `<!-- ${name}:end -->`;
  const i = html.indexOf(open);
  const j = html.indexOf(close);
  if (i === -1 || j === -1 || j < i) {
    throw new Error(`injectRegion: missing region ${name}:start/${name}:end`);
  }
  return html.slice(0, i + open.length) + payload + html.slice(j);
}

/** Verbatim copy of the canonical token CSS → _tokens.css (DRY; no regex extraction). */
export function extractTokens() {
  const src = join(BRAND, 'colors_and_type.css');
  const css = readFileSync(src, 'utf8');
  const header = `/* GENERATED by design-system/build.mjs — verbatim copy of\n   website/public/brand/mentolder/colors_and_type.css. Do not edit by hand. */\n`;
  writeFileSync(join(HERE, '_tokens.css'), header + css);
}

/** Copy the SVGs the icon-sheet & logo cards inline into assets/ (tracked local snapshot). */
export function copyAssets() {
  for (const sub of ['props', 'logos']) {
    const from = join(BRAND, sub);
    const to = join(HERE, 'assets', sub);
    mkdirSync(to, { recursive: true });
    for (const f of readdirSync(from).filter((n) => n.endsWith('.svg'))) {
      copyFileSync(join(from, f), join(to, f));
    }
  }
}

/** Inline every *.svg in absDir as a labelled grid cell. */
export function svgGrid(absDir) {
  return readdirSync(absDir)
    .filter((n) => n.endsWith('.svg'))
    .sort()
    .map((n) => {
      const svg = readFileSync(join(absDir, n), 'utf8')
        .replace(/<\?xml[^>]*\?>/, '')
        .trim();
      const label = basename(n, '.svg');
      return `<div class="icon-cell">${svg}<span class="cap">${label}</span></div>`;
    })
    .join('\n');
}

/** Assemble one card: inject tokens, shared card css, and any svg grids. */
export function assembleCard(html) {
  const tokens = `<style>\n${readFileSync(join(HERE, '_tokens.css'), 'utf8')}\n</style>`;
  const card = `<style>\n${readFileSync(join(HERE, '_card.css'), 'utf8')}\n</style>`;
  let out = injectRegion(html, 'tokens', tokens);
  out = injectRegion(out, 'card', card);
  if (out.includes('<!-- props-grid:start -->')) {
    out = injectRegion(out, 'props-grid', svgGrid(join(HERE, 'assets', 'props')));
  }
  if (out.includes('<!-- logos-grid:start -->')) {
    out = injectRegion(out, 'logos-grid', svgGrid(join(HERE, 'assets', 'logos')));
  }
  return out;
}

export async function main() {
  extractTokens();
  copyAssets();
  if (!existsSync(CARDS)) { console.log('no cards/ yet'); return; }
  const files = readdirSync(CARDS).filter((n) => n.endsWith('.html')).sort();
  for (const f of files) {
    const p = join(CARDS, f);
    writeFileSync(p, assembleCard(readFileSync(p, 'utf8')));
  }
  console.log(`assembled ${files.length} card(s)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
